### ISSUE TITLE
0.4.10 SHA256 mismatch

### ISSUE THREAD

**Issue by davebryson** [ethereum/homebrew-ethereum#106]
Getting an error related to mismatched sha256:

`
==> Upgrading 1 outdated package, with result:
ethereum/ethereum/solidity 0.4.10
==> Upgrading ethereum/ethereum/solidity 
==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.10/solidity_0.4.10.tar.gz
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/40892817/f3804bea-09ae-11e7-8354-b693032ea3cf.gz?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%

Error: SHA256 mismatch

Expected: 542a0613f700ff2bd58932307c96a89a702541eb84c8c6bfe3817e70df55ac24
Actual: a1103f91d240101a90c9bec5243f2436563d3772c4571a352ea7bc21de8706d1
`

**Comment by Beasta** [comment]
I'm having the same issue. I just installed version 4.9 using

brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/8d77bba3c9a682b507d923b336bd61558e25d329/solidity.rb

**Comment by beatrizsanchez** [comment]
Same issue (https://github.com/ethereum/go-ethereum/issues/3796)

**Comment by chriseth** [comment]
Should have been solved by now, please retry.

**Comment by beatrizsanchez** [comment]
Thanks! :)

**Comment by chriseth** [comment]
@beatrizsanchez so did it work?

**Comment by beatrizsanchez** [comment]
It did indeed.

**Comment by chriseth** [comment]
Thanks!

**Comment by davebryson** [comment]
Working like a charm now.  Thanks!!

**Comment by linchangting** [comment]
@davebryson I have the same issue. Did you solve it?

**Comment by chriseth** [comment]
@linchangting for the current version?

**Comment by linchangting** [comment]
@chriseth the current version is ok，however I need the 0.4.10...T﹏T
I have the same issue when I brew install solidity 0.4.10

**Comment by john-osullivan** [comment]
I need to use Solidity 0.4.11 and am running into this issue when installing via brew:

`brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/2de22833e3182e68d16ee490e8a62f556a0c5a5f/solidity.rb`

Was the "solution" to abandon the mismatched versions and use upgraded ones?
