### ISSUE TITLE
Mining on MacBookPro issue with cpp-ethereum

### ISSUE THREAD

**Issue by romanmagdavs** [ethereum/homebrew-ethereum#111]
Hi All,

Running the following command failed:

$ brew reinstall cpp-ethereum --with-gpu-mining --devel --headless --build-from-source
Warning: Calling build.build_bottle? is deprecated!
Use build.bottle? instead.
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:37:in `reinstall_formula'

==> Reinstalling ethereum/ethereum/cpp-ethereum 
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --headless option so it will be ignored!
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --with-gpu-mining option so it will be ignored!
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/romanmagda/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/romanmagda/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
CMake Error in test/CMakeLists.txt:
  Target "web3jsonrpc" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "MHD_INCLUDE_DIR-NOTFOUND"

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    HAVE_CLOCK_GETTIME

-- Build files have been written to: /tmp/cpp-ethereum-20170526-16385-1f7a4yx

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

Please help me to solve the issue, thank you very much !

Roman

**Comment by matiwinnetou** [comment]
+1, same issue here

**Comment by matiwinnetou** [comment]
this maybe the reason:

**Comment by romanmagdavs** [comment]
Hi, thank you very much for your answer, it was really hepful.

Kind regards,
Roman
