### ISSUE TITLE
install error on 10.10.5 

### ISSUE THREAD

**Issue by jasperboyd** [ethereum/homebrew-ethereum#113]
Got this on Yosemite 10.10.5 (14F2411), tried reinstalling all my homebrew dependencies, xcode, but to no avail. Any thoughts?

`Last 15 lines from /Users/jasperboyd/Library/Logs/Homebrew/cpp-ethereum/02.make:
        TransactionReceipt(h256 _root, u256 _gasUsed, LogEntries const& _log);
        ^
[ 82%] Linking CXX executable eth
cd /tmp/cpp-ethereum-20170605-39158-1rb9939/eth && /usr/local/Cellar/cmake/3.8.2/bin/cmake -E cmake_link_script CMakeFiles/eth.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/eth.dir/AccountManager.cpp.o CMakeFiles/eth.dir/main.cpp.o  -o eth ../libevm/libevm.a ../libweb3jsonrpc/libweb3jsonrpc.a ../libwebthree/libwebthree.a ../evmjit/libevmjit/libevmjit.a ../libethashseal/libethashseal.a ../libethash/libethash.a ../libethereum/libethereum.a ../libevm/libevm.a ../libevmcore/libevmcore.a ../evmjit/libevmjit/libevmjit.a ../deps/lib/libLLVMMCJIT.a ../deps/lib/libLLVMX86CodeGen.a ../deps/lib/libLLVMX86Desc.a ../deps/lib/libLLVMX86Info.a ../deps/lib/libLLVMMCDisassembler.a ../deps/lib/libLLVMX86AsmPrinter.a ../deps/lib/libLLVMX86Utils.a ../deps/lib/libLLVMSelectionDAG.a ../deps/lib/libLLVMAsmPrinter.a ../deps/lib/libLLVMDebugInfoCodeView.a ../deps/lib/libLLVMCodeGen.a ../deps/lib/libLLVMBitWriter.a ../deps/lib/libLLVMipo.a ../deps/lib/libLLVMInstrumentation.a ../deps/lib/libLLVMVectorize.a ../deps/lib/libLLVMScalarOpts.a ../deps/lib/libLLVMLinker.a ../deps/lib/libLLVMIRReader.a ../deps/lib/libLLVMAsmParser.a ../deps/lib/libLLVMInstCombine.a ../deps/lib/libLLVMTransformUtils.a ../deps/lib/libLLVMExecutionEngine.a ../deps/lib/libLLVMTarget.a ../deps/lib/libLLVMAnalysis.a ../deps/lib/libLLVMProfileData.a ../deps/lib/libLLVMRuntimeDyld.a ../deps/lib/libLLVMObject.a ../deps/lib/libLLVMMCParser.a ../deps/lib/libLLVMBitReader.a ../deps/lib/libLLVMMC.a ../deps/lib/libLLVMCore.a ../deps/lib/libLLVMSupport.a -lpthread ../libethcore/libethcore.a ../libwhisper/libwhisper.a ../libp2p/libp2p.a ../libdevcrypto/libdevcrypto.a ../libdevcore/libdevcore.a ../deps/src/boost/stage/lib/libboost_filesystem.a ../deps/src/boost/stage/lib/libboost_system.a ../deps/src/boost/stage/lib/libboost_random.a ../deps/src/boost/stage/lib/libboost_thread.a ../deps/src/boost/stage/lib/libboost_chrono.a ../deps/src/boost/stage/lib/libboost_date_time.a ../deps/src/boost/stage/lib/libboost_regex.a /usr/local/lib/libleveldb.dylib /usr/local/lib/libsnappy.dylib ../deps/lib/libsecp256k1.a ../deps/lib/libcryptopp.a ../utils/libscrypt/libscrypt.a ../deps/lib/libjsonrpccpp-server.a ../deps/lib/libjsonrpccpp-common.a ../deps/lib/libjsoncpp.a /usr/local/lib/libmicrohttpd.dylib
[ 82%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtesteth/boostTest.cpp.o
cd /tmp/cpp-ethereum-20170605-39158-1rb9939/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170605-39158-1rb9939 -I/tmp/cpp-ethereum-20170605-39158-1rb9939/include -I/tmp/cpp-ethereum-20170605-39158-1rb9939/test/.. -I/tmp/cpp-ethereum-20170605-39158-1rb9939/test/../utils -isystem /tmp/cpp-ethereum-20170605-39158-1rb9939/deps/include -isystem /tmp/cpp-ethereum-20170605-39158-1rb9939/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170605-39158-1rb9939/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtesteth/boostTest.cpp.o -c /tmp/cpp-ethereum-20170605-39158-1rb9939/test/tools/libtesteth/boostTest.cpp
[ 83%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtestutils/BlockChainLoader.cpp.o
cd /tmp/cpp-ethereum-20170605-39158-1rb9939/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170605-39158-1rb9939 -I/tmp/cpp-ethereum-20170605-39158-1rb9939/include -I/tmp/cpp-ethereum-20170605-39158-1rb9939/test/.. -I/tmp/cpp-ethereum-20170605-39158-1rb9939/test/../utils -isystem /tmp/cpp-ethereum-20170605-39158-1rb9939/deps/include -isystem /tmp/cpp-ethereum-20170605-39158-1rb9939/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170605-39158-1rb9939/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtestutils/BlockChainLoader.cpp.o -c /tmp/cpp-ethereum-20170605-39158-1rb9939/test/tools/libtestutils/BlockChainLoader.cpp
1 error generated.
make[2]: *** [test/CMakeFiles/testeth.dir/tools/libtesteth/ImportTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 83%] Built target eth
make[1]: *** [test/CMakeFiles/testeth.dir/all] Error 2
make: *** [all] Error 2`

**Comment by jasperboyd** [comment]
last attempt yielded slightly different error

`
Last 15 lines from /Users/jasperboyd/Library/Logs/Homebrew/cpp-ethereum/02.make:
[ 83%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtestutils/FixedClient.cpp.o
[ 83%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtesteth/boostTest.cpp.o
[ 83%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtestutils/Common.cpp.o
[ 83%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtestutils/BlockChainLoader.cpp.o
cd /tmp/cpp-ethereum-20170606-20025-xckn3h/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170606-20025-xckn3h -I/tmp/cpp-ethereum-20170606-20025-xckn3h/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/.. -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/../utils -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/include -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtestutils/FixedClient.cpp.o -c /tmp/cpp-ethereum-20170606-20025-xckn3h/test/tools/libtestutils/FixedClient.cpp
cd /tmp/cpp-ethereum-20170606-20025-xckn3h/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170606-20025-xckn3h -I/tmp/cpp-ethereum-20170606-20025-xckn3h/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/.. -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/../utils -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/include -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtestutils/Common.cpp.o -c /tmp/cpp-ethereum-20170606-20025-xckn3h/test/tools/libtestutils/Common.cpp
cd /tmp/cpp-ethereum-20170606-20025-xckn3h/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170606-20025-xckn3h -I/tmp/cpp-ethereum-20170606-20025-xckn3h/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/.. -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/../utils -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/include -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtestutils/BlockChainLoader.cpp.o -c /tmp/cpp-ethereum-20170606-20025-xckn3h/test/tools/libtestutils/BlockChainLoader.cpp
cd /tmp/cpp-ethereum-20170606-20025-xckn3h/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170606-20025-xckn3h -I/tmp/cpp-ethereum-20170606-20025-xckn3h/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/.. -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/../utils -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/include -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtesteth/boostTest.cpp.o -c /tmp/cpp-ethereum-20170606-20025-xckn3h/test/tools/libtesteth/boostTest.cpp
[ 84%] Building CXX object test/CMakeFiles/testeth.dir/tools/libtestutils/StateLoader.cpp.o
cd /tmp/cpp-ethereum-20170606-20025-xckn3h/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_EVMJIT -DETH_FATDB -I/tmp/cpp-ethereum-20170606-20025-xckn3h -I/tmp/cpp-ethereum-20170606-20025-xckn3h/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/.. -I/tmp/cpp-ethereum-20170606-20025-xckn3h/test/../utils -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/include -isystem /tmp/cpp-ethereum-20170606-20025-xckn3h/deps/src/boost -isystem /usr/local/include -I/tmp/cpp-ethereum-20170606-20025-xckn3h/evmjit/include  -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -Wall -Wextra -Werror -Wno-unknown-pragmas -fstack-protector -fstack-protector-strong -std=c++11 -o CMakeFiles/testeth.dir/tools/libtestutils/StateLoader.cpp.o -c /tmp/cpp-ethereum-20170606-20025-xckn3h/test/tools/libtestutils/StateLoader.cpp
1 error generated.
make[2]: *** [test/CMakeFiles/testeth.dir/tools/libtesteth/ImportTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [test/CMakeFiles/testeth.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by jebuscraisp** [comment]
Am getting the same Error 2.
:(
https://github.com/ethereum/homebrew-ethereum/issues/116

**Comment by jasperboyd** [comment]
Had success with `brew install CryptoPP` and `brew install --devel --successful` to grab latest build that passed CI
