### ISSUE TITLE
Import formula into Homebrew/homebrew-core

### ISSUE THREAD

**Issue by MikeMcQuaid** [ethereum/homebrew-ethereum#115]
Hi! This is a really popular formula amongst Homebrew users. How would you feel about an `ethereum` formula in Homebrew/homebrew-core? Thanks!

**Comment by fjl** [comment]
Sorry, I didn't see this issue until now. go-ethereum updates rather often and some updates are mandatory (i.e. when there's a hard fork). I'll bring it up with the team.

**Comment by MikeMcQuaid** [comment]
@fjl Any news/thoughts? Thanks!

**Comment by axic** [comment]
@MikeMcQuaid what is the process of updating brews in core?

**Comment by axic** [comment]
It seems updates must be made as PR to that repo and worst case it seems to take a week to merge a version update (but usually looks like it is handled within 2 days).

That might be problematic, because whenever a new geth or solidity release is made people demand it to be available instantly on homebrew too.

**Comment by MikeMcQuaid** [comment]
@axic Submitting a pull request or using `brew bump-formula-pr`. @ilovezfs generally mass updates things so unless our CI fails (i.e. the update has broken things) updates happen very quickly.

**Comment by axic** [comment]
I think from Solidity's perspective (correct me @chriseth if I'm wrong) if version bumps can be merged within a day (<= 24 hours) it could be possible to move, though preferable would be something like within 6-8 hours.

Is that a far fetched requirement?

**Comment by axic** [comment]
One more important question is though: who is allowed to update the brews? Is it possible for a malicious actor to update a brew to a potentially malicious repository?

**Comment by chriseth** [comment]
Yes, 24 hours are fine.

**Comment by MikeMcQuaid** [comment]
> I think from Solidity's perspective (correct me @chriseth if I'm wrong) if version bumps can be merged within a day (<= 24 hours) it could be possible to move, though preferable would be something like within 6-8 hours.
> 
> Is that a far fetched requirement?

If a version bump is literally just a version bump and CI passes so it's not breaking anything: yes, that's a reasonable expectation. It's not a reasonable _requirement_ just because we're a volunteer run product who don't provide an SLA etc.

As a flip side I'd like to gently suggest that issues like https://github.com/ethereum/homebrew-ethereum/pull/136 would have been fixed by the Homebrew/homebrew-core maintainers weeks ago so I do think the experience for everyone will be improved.

> One more important question is though: who is allowed to update the brews? Is it possible for a malicious actor to update a brew to a potentially malicious repository?

Homebrew maintainers are the only ones who can merge pull requests to update formulae. All these are reviewed by a human before merging.

**Comment by ilovezfs** [comment]
FYI, `geth` is already in Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/blob/master/Formula/geth.rb

**Comment by ilovezfs** [comment]
Here is what it installs:
```
iMac-TMP:~ joe$ brew install geth
==> Downloading https://homebrew.bintray.com/bottles/geth-1.7.3.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring geth-1.7.3.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/geth/1.7.3: 16 files, 159.9MB
iMac-TMP:~ joe$ find /usr/local/Cellar/geth/1.7.3
/usr/local/Cellar/geth/1.7.3
/usr/local/Cellar/geth/1.7.3/.brew
/usr/local/Cellar/geth/1.7.3/.brew/geth.rb
/usr/local/Cellar/geth/1.7.3/AUTHORS
/usr/local/Cellar/geth/1.7.3/COPYING
/usr/local/Cellar/geth/1.7.3/INSTALL_RECEIPT.json
/usr/local/Cellar/geth/1.7.3/README.md
/usr/local/Cellar/geth/1.7.3/bin
/usr/local/Cellar/geth/1.7.3/bin/abigen
/usr/local/Cellar/geth/1.7.3/bin/bootnode
/usr/local/Cellar/geth/1.7.3/bin/evm
/usr/local/Cellar/geth/1.7.3/bin/examples
/usr/local/Cellar/geth/1.7.3/bin/faucet
/usr/local/Cellar/geth/1.7.3/bin/geth
/usr/local/Cellar/geth/1.7.3/bin/p2psim
/usr/local/Cellar/geth/1.7.3/bin/puppeth
/usr/local/Cellar/geth/1.7.3/bin/rlpdump
/usr/local/Cellar/geth/1.7.3/bin/swarm
/usr/local/Cellar/geth/1.7.3/bin/wnode
iMac-TMP:~ joe$ 
```

**Comment by axic** [comment]
It would be nice to have #161 fixed 😉

**Comment by MikeMcQuaid** [comment]
@axic We will be responsible for fixing issues users have with this formula when it's in Homebrew/homebrew-core, not before, sorry.

**Comment by MikeMcQuaid** [comment]
@axic I've opened https://github.com/ethereum/homebrew-ethereum/pull/166 as the formula is already present in Homebrew/core.

**Comment by axic** [comment]
`cpp-ethereum`? The build issue is with that.

I think homebrew-core only has go-ethereum (`geth.rb` in homebrew-core, `ethereum.rb` here), but I may be bad at searching.

Also I didn't know one could move certain formulas and not others, that is handy.
