### ISSUE TITLE
Go Ethereum formula not exporting environment variables?

### ISSUE THREAD

**Issue by simondlr** [ethereum/homebrew-ethereum#12]
I installed go-ethereum.

Then stumbled upon QT 5.4 issue. Trying to switch back to 5.3.2 I need to use $GOPATH (https://github.com/ethereum/go-ethereum/issues/212). But it is not there.

Reinstalled to verify. And when I do go env, this is what it looks like.

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

Any clues? I can manually export it. But why isn't the formula doing its job properly? 

    ENV["PKG_CONFIG_PATH"] = "#{HOMEBREW_PREFIX}/opt/qt5/lib/pkgconfig"
    ENV["QT5VERSION"] = `pkg-config --modversion Qt5Core`
    ENV["CGO_CPPFLAGS"] = "-I#{HOMEBREW_PREFIX}/opt/qt5/include/QtCore"
    ENV["GOPATH"] = "#{buildpath}"
    ENV["GOROOT"] = "#{HOMEBREW_PREFIX}/opt/go/libexec"

Am I missing something here?

**Comment by caktux** [comment]
The formula will never be setting those environment variables permanently, only while building, so it's doing its job properly. Use `brew switch qt5 5.3.2` instead of that complicated downgrade.
