### ISSUE TITLE
Mac OS X 10.12.5 install error for cpp-ethereum

### ISSUE THREAD

**Issue by Proteles** [ethereum/homebrew-ethereum#120]
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Using the sandbox
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/amanns/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
==> make
Last 15 lines from /Users/amanns/Library/Logs/Homebrew/cpp-ethereum/02.make:
[100%] Building CXX object lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/WinEHPrepare.cpp.o
[100%] Building CXX object lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/XRayInstrumentation.cpp.o
[100%] Linking CXX static library ../libLLVMCodeGen.a
[100%] Built target LLVMCodeGen
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/deps && /usr/local/Cellar/cmake/3.9.0/bin/cmake -E touch /tmp/cpp-ethereum-20170801-69752-moxjkf/deps/src/llvm-stamp/./llvm-build
[ 31%] Performing install step for 'llvm'
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/deps && /usr/local/Cellar/cmake/3.9.0/bin/cmake -P /tmp/cpp-ethereum-20170801-69752-moxjkf/deps/src/llvm-stamp/llvm-install-Release.cmake
-- llvm install command succeeded.  See also /tmp/cpp-ethereum-20170801-69752-moxjkf/deps/src/llvm-stamp/llvm-install-*.log
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/deps && /usr/local/Cellar/cmake/3.9.0/bin/cmake -E touch /tmp/cpp-ethereum-20170801-69752-moxjkf/deps/src/llvm-stamp/./llvm-install
[ 31%] Completed 'llvm'
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/evmjit && /usr/local/Cellar/cmake/3.9.0/bin/cmake -E make_directory /tmp/cpp-ethereum-20170801-69752-moxjkf/evmjit/CMakeFiles/.
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/evmjit && /usr/local/Cellar/cmake/3.9.0/bin/cmake -E touch /tmp/cpp-ethereum-20170801-69752-moxjkf/evmjit/CMakeFiles/./llvm-complete
cd /tmp/cpp-ethereum-20170801-69752-moxjkf/evmjit && /usr/local/Cellar/cmake/3.9.0/bin/cmake -E touch /tmp/cpp-ethereum-20170801-69752-moxjkf/deps/src/llvm-stamp/./llvm-done
[ 31%] Built target llvm
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

**Comment by ashokkumarrathore** [comment]
version 10.12.6. Same error.

**Comment by crazymaster49** [comment]
I am having the same problem.  Has anyone had it to work on a previous update?

**Comment by igordelorenzi** [comment]
Same problem here. Is there any lack of dependency?

**Comment by quixoticblink** [comment]
I am also having the same error in 10.12.6...anyone solved the issue ?

**Comment by WM520** [comment]
have anyone solve this problem? I have  a same issue

**Comment by arytbk** [comment]
Same issue!

**Comment by stemwinder** [comment]
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/josh/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release -DEVMJIT=1
Last 15 lines from /Users/josh/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:115 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_finalize.cmake:69 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171026-65177-130bsce/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mac OS X 10.12.5 install error https://github.com/ethereum/homebrew-ethereum/issues/120
Error installing go-ethereum on Mac OS X https://github.com/ethereum/homebrew-ethereum/issues/117
Mining on MacBookPro issue https://github.com/ethereum/homebrew-ethereum/issues/111
XcodeDefault.xctoolchain/usr/bin/ranlib: file: libsolidity.a(AsmAnalysisInfo.cpp.o) has no symbols https://github.com/ethereum/homebrew-ethereum/issues/128
Add a dependency on jsoncpp for solidity? https://github.com/ethereum/homebrew-ethereum/issues/123
Macbook Pro - Radeon Pro 560 4GB of GDDR5 issues https://github.com/ethereum/homebrew-ethereum/issues/122
Error when installing Solidity compiler https://github.com/ethereum/homebrew-ethereum/issues/96

**Comment by jedgecombe** [comment]
same issue for me too!

**Comment by SwathiKadambala** [comment]
same issue for me too!

brew reinstall cpp-ethereum
==> Reinstalling ethereum/ethereum/cpp-ethereum 
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/swathik/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/loca
Last 15 lines from /Users/swathik/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:115 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_finalize.cmake:69 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171031-11816-ms6r64/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mac OS X 10.12.5 install error https://github.com/ethereum/homebrew-ethereum/issues/120
Error installing go-ethereum on Mac OS X https://github.com/ethereum/homebrew-ethereum/issues/117
Mining on MacBookPro issue https://github.com/ethereum/homebrew-ethereum/issues/111
XcodeDefault.xctoolchain/usr/bin/ranlib: file: libsolidity.a(AsmAnalysisInfo.cpp.o) has no symbols https://github.com/ethereum/homebrew-ethereum/issues/128
Add a dependency on jsoncpp for solidity? https://github.com/ethereum/homebrew-ethereum/issues/123
Macbook Pro - Radeon Pro 560 4GB of GDDR5 issues https://github.com/ethereum/homebrew-ethereum/issues/122
Error when installing Solidity compiler https://github.com/ethereum/homebrew-ethereum/issues/96

**Comment by Henripru** [comment]
Same issue
