### ISSUE TITLE
brew install cpp-ethereum error

### ISSUE THREAD

**Issue by webfrank** [ethereum/homebrew-ethereum#121]
Darwin iMac27 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

iMac27:~ francesco$ brew install cpp-ethereum --devel --successfull
Updating Homebrew...
==> Installing cpp-ethereum from ethereum/ethereum
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --successfull option so it will be ignored!
==> Using the sandbox
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/francesco/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE
Last 15 lines from /Users/francesco/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:106 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_finalize.cmake:66 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:96 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20170807-38650-1hikrrr/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

**Comment by bassrock** [comment]
Seeing the same issue.

**Comment by jonnyhsy** [comment]
Same here

**Comment by ruslo** [comment]
> https://github.com/ruslo/hunter/wiki/error.internal

This is a current peculiarity of error in logs. I've managed to run install on my local machine and in `01.cmake` file I've found the origin of the problem:
* https://github.com/ruslo/hunter/wiki/error.no.toolchain.info

I need to analyze is compiler able to build this code:
```cpp
#if defined(__cplusplus)
# pragma message("Hello")
#endif
```

However I can't start `/usr/local/Homebrew/Library/Homebrew/shims/super/clang++` which is used in brew:
```
> /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ --version
clang++: The build tool has reset ENV; --env=std required.
```

What should I do about it?

Note that if you're using Hunter you don't have to manage dependencies with brew. This code is redundant:
* https://github.com/ethereum/homebrew-ethereum/blob/de1da16f7972a899fc8dd1f3f04299eced6f4312/cpp-ethereum.rb#L40-L46

**Comment by albedoweb** [comment]
Same error
OS version: 10.11.6

**Comment by rohitgoyal** [comment]
Same issue
OS: 10.12.5

**Comment by Mnasovo** [comment]
same issue ... OS 10.12.6 (16G29)

**Comment by rmf34** [comment]
same issue 10.12.6 (16G29)

**Comment by nicexe** [comment]
same issue on OSX: 10.10.5

**Comment by phortx** [comment]
Same.

**Comment by albedoweb** [comment]
I was able to build miner from https://github.com/ArtSabintsev/Ethminer-for-macOS repo.
You can follow instruction on main page. Hope it will help someone.

**Comment by Maviza101** [comment]
The following instructions solved it for me:

* Install Xcode or the CLI from developer.apple.com/xcode.

* Open your terminal and enter the following commands:

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew reinstall llvm

```
* At this point, close the terminal, and relaunch it.


* Then enter the following commands in the terminal:

```
brew install leveldb libmicrohttpd cryptopp
brew install cpp-ethereum --devel --successful --verbose

```

You can check [this conversation](https://github.com/ethereum/homebrew-ethereum/issues/116) for any other details you need.

**Comment by paradoxlogic-de** [comment]
same issue: mac OS Sierra 10.12.6 (16G29)

**Comment by joshtharakan** [comment]
same issue here. Hopefully i can use @Maviza101 instructions

**Comment by dhirenraghu** [comment]
@Maviza101 Thank you, It worked!

**Comment by desve** [comment]
I run brew reinstall llvm and restart the terminal/console after installing xcode. But I have the mistake.

==> Configuration
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0907abefa0e561f075d86cf213e2d089ca948646
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local/opt/curl:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/gperftools/lib/pkgconfig:/usr/local/opt/argtable/lib/pkgconfig:/usr/local/opt/jsoncpp/lib/pkgconfig:/usr/local/opt/libmicrohttpd/lib/pkgconfig:/usr/local/opt/hiredis/lib/pkgconfig:/usr/local/opt/libjson-rpc-cpp/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/local/opt/curl/bin:/usr/local/opt/gperftools/bin:/usr/local/opt/leveldb/bin:/usr/local/opt/libjson-rpc-cpp/bin:/usr/local/opt/miniupnpc/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: ethereum/ethereum/cpp-ethereum 1.3.0 did not build
Logs:
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/00.options.out
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/01.cmake
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/01.cmake.cc
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/02.make
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/02.make.cc
     /Users/vladimirdesatov/Library/Logs/Homebrew/cpp-ethereum/CMakeCache.txt
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124

Help me please

**Comment by vecerek** [comment]
The same here as @desve

**Comment by alannguyen246** [comment]
I'm getting exactly the same issue as you guys and I've tried the above and it hasn't worked. Does anyone suggest anything different? Thanks 
Alan

**Comment by quixoticblink** [comment]
Same issue and says  **Error: Failed to download resource "cpp-ethereum"**

brew install cpp-ethereum --devel --successful --verbose
==> Installing cpp-ethereum from ethereum/ethereum
/usr/bin/sandbox-exec -f /tmp/homebrew20171001-63447-smidw4.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb --verbose --devel --successful
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/kaul/Library/Caches/Homebrew/cpp-ethereum--git
git config remote.origin.url https://github.com/ethereum/cpp-ethereum.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
==> Checking out revision 4943d3eeae865537e18c410e5e7d064825bf2711
git checkout -f 4943d3eeae865537e18c410e5e7d064825bf2711 --
HEAD is now at 4943d3eea... Merge pull request #3063 from bobsummerwill/develop
git reset --hard 4943d3eeae865537e18c410e5e7d064825bf2711
HEAD is now at 4943d3eea Merge pull request #3063 from bobsummerwill/develop
git submodule foreach --recursive git submodule sync
Entering 'deps'
Entering 'evmjit'
git submodule update --init --recursive
error: Server does not allow request for unadvertised object 2dac53454a93d7d2693a1411cfd8fbbff97f5770
Fetched in submodule path 'evmjit', but it did not contain 2dac53454a93d7d2693a1411cfd8fbbff97f5770. Direct fetching of that commit failed.
Error: Failed to download resource "cpp-ethereum"
Failure while executing: git submodule update --init --recursive

**Comment by tebeshir** [comment]
I have the same problem:

Fetched in submodule path 'evmjit', but it did not contain 2dac53454a93d7d2693a1411cfd8fbbff97f5770. Direct fetching of that commit failed.

**Comment by alailsonribeiro** [comment]
See #185
