### ISSUE TITLE
Macbook Pro - Radeon Pro 560 4GB of GDDR5 issues with cpp-ethereum/ethminer

### ISSUE THREAD

**Issue by jmfronsee** [ethereum/homebrew-ethereum#122]
First issue started out on this thread, and ArtSabintsev helped me work through and get everything installed on Macbook.  But got off track on my second issue, starting new here.  Here is initial related thread:

https://github.com/ethereum/homebrew-ethereum/issues/116#issuecomment-318781981

Macbook Pro has integrated Intel HD Graphics.  Plus the dedicated GPU in the title, which is the GPU I want to try mining with.

A sample "main command":

$ ./ethminer -G -S YOUR_MINING_POOL_ADDRESS -O YOUR_MINING_POOL_WALLET_ADDRESS --opencl-device 1

-Try putting 0 or 1 as the --opencl-device value. It doesnt matter, if you watch the output carefully it says

"Found suitable OpenCL device [ Intel(R) HD Graphics 630 ] with 1610612736 bytes of GPU memory".

-That is only 1.6GB of memory. It appears to be using the onboard Intel GPU no matter what I put in. My dedicated Radeon Pro 560 has 4GB memory, and if it indeed was using that GPU, would be netting MUCH higher than the ~ 1.5 MH/s that I was getting with this setup - this 4GB GPU would be getting more like 20+ MH/s I would imagine. I tried messing with the "--opencl-platform" parameters and got the same results, and '1' it wont even run.

If it is indeed the Intel GPU running every time (only thing that explains 1.5 MH/s), HOW is it running. The Ethereum DAG file is well over 1.6 GB, so the Intel must be using shared system memory or something to load the DAG.

Maybe this issue has something to do with the automatic graphics switching these newer Macs use.

Side note issue: I have yet to get the miner to run successfully again, not even at the 1.5 MH/s rate. No error messages, the terminal just stops outputting. So many problems with this setup.    How can I successfully target my dedicated GPU?

Other areas I brought up this issue:

https://steemit.com/mining/@soon8013/how-to-mine-eth-with-gpu-on-your-mac
https://forum.minergate.com/viewtopic.php?f=9&t=3287

Other people having same issue sounds like:

https://github.com/ethereum/cpp-ethereum/issues/3116
https://forum.ethereum.org/discussion/2880/how-to-tell-ethminer-which-gpu-to-use

- ArtSabintsev you must be able to reproduce this issue easily if you have a modern Macbook with graphics switching.  You never ran into this issue???

THANK YOU

**Comment by ArtSabintsev** [comment]
Just happened to come to this by chance. Will look when I have time. Next time, feel free to @ me so I get the notification :)

**Comment by ArtSabintsev** [comment]
Honestly, I have no idea how to deal with this issue. I only ever tried GPU mining, which neither of my computers could deal with as the current DAG requires more than I currently have.

**Comment by chfast** [comment]
Take ethminer from: https://github.com/ethereum-mining/ethminer.
