### ISSUE TITLE
error while instally solidity 0.4.16 on OS X

### ISSUE THREAD

**Issue by adridadou** [ethereum/homebrew-ethereum#125]
When I run "brew install solidity"  I get a silent error:
[ 65%] Built target solidity
make: *** [all] Error 2

But then I tried to install it from source and I got this error:

Undefined symbols for architecture x86_64:
  "Json::Value::append(Json::Value&&)", referenced from:
      dev::eth::Assembly::streamAsmJson(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&) const in libevmasm.a(Assembly.cpp.o)
ld: symbol(s) not found for architecture x86_64

**Comment by adridadou** [comment]
the issue came from the fact that I did a brew upgrade
that installed jsoncpp 1.8.3
this new version made some code in solc deprecated and therefore it wasn't building anymore

**Comment by onetom** [comment]
More specifically (as advised by @acote88):

```
brew switch jsoncpp 1.8.1
brew reinstall solidity
```

**Comment by heavyk** [comment]
if you get `Error: jsoncpp does not have a version "1.8.1" in the Cellar.`, unlinking it worked for me

```
brew unlink jsoncpp
brew reinstall solidity
```
