### ISSUE TITLE
cpp-ethereum issue on mac: CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):

### ISSUE THREAD

**Issue by tmajor90** [ethereum/homebrew-ethereum#129]
I'm trying to install cpp-ethereum, and get this error.. can anyone help with some suggestions how to solve it?

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:115 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_finalize.cmake:69 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)

**Comment by joshjung** [comment]
I have this same issue.

**Comment by sporknak** [comment]
Same here.

**Comment by simocosimo** [comment]
Same!

**Comment by hbwhite-edu** [comment]
Same

**Comment by mbrennan** [comment]
Same

**Comment by sporknak** [comment]
I've updated everything to the latest and greatest and can't get cpp-ethereum installed. Below is the full error message...

> ==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -DCMAKE_
Last 15 lines from /Users/sporknak/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:115 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_finalize.cmake:69 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171112-9140-1qlga1d/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mac OS X 10.12.5 install error https://github.com/ethereum/homebrew-ethereum/issues/120
Error installing go-ethereum on Mac OS X https://github.com/ethereum/homebrew-ethereum/issues/117
Mining on MacBookPro issue https://github.com/ethereum/homebrew-ethereum/issues/111
XcodeDefault.xctoolchain/usr/bin/ranlib: file: libsolidity.a(AsmAnalysisInfo.cpp.o) has no symbols https://github.com/ethereum/homebrew-ethereum/issues/128
Issue on mac: CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message): https://github.com/ethereum/homebrew-ethereum/issues/129
Add a dependency on jsoncpp for solidity? https://github.com/ethereum/homebrew-ethereum/issues/123
Macbook Pro - Radeon Pro 560 4GB of GDDR5 issues https://github.com/ethereum/homebrew-ethereum/issues/122
Error when installing Solidity compiler https://github.com/ethereum/homebrew-ethereum/issues/96

**Comment by andrewztan** [comment]
same issue

**Comment by sporknak** [comment]
I ran this again and Homebrew had an update which included an update to cmake. Still fails.

> ==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local
Last 15 lines from /Users/sporknak/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:115 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_finalize.cmake:69 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171118-3156-1m0pgm1/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126

**Comment by trungda** [comment]
I am having the same issue. Has anyone resolved this?

**Comment by miroslavbucek** [comment]
same issue

**Comment by lucasdaiki** [comment]
same :/

**Comment by rbostan** [comment]
same issue :/

**Comment by quantoid** [comment]
me to

**Comment by shiro83** [comment]
same issue (´・ω・｀)

**Comment by ton4ar** [comment]
Same (^_^)/

**Comment by awagner12** [comment]
Same

**Comment by TMajorTecRacer** [comment]
Did anyone find any solution for this?

**Comment by rainmetersjtu** [comment]
same issue...

**Comment by daniel-lahoz** [comment]
Same here.. :(

```
CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:103 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171221-5865-1kq2g1z/CMakeFiles/CMakeOutput.log".

```

**Comment by bobio7** [comment]
Same issue. Also tried reinstall llvm disn’t Fix it.

Anyone found a workaround?

**Comment by FlobsterHH** [comment]
Same here. Also tried reinstall llvm. Anything new?

**Comment by wind2412** [comment]
Same as above.

**Comment by zallanx** [comment]
Same issue.

**Comment by wudongyang** [comment]
Same issue

```
CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:103 (hunter_add_package)



```

**Comment by benhardy** [comment]
same

**Comment by leastXpctdMost** [comment]
`CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:106 (hunter_add_package)`

**Comment by leastXpctdMost** [comment]
> `CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:106 (hunter_add_package)`

**Comment by shulmda** [comment]
Same

**Comment by chfast** [comment]
@ruslo, can you take a look at this Hunter error?

**Comment by ruslo** [comment]
> can you take a look at this Hunter error?

```
-- [hunter] Calculating Toolchain-SHA1

[hunter ** FATAL ERROR **] No toolchain info generated
[hunter ** FATAL ERROR **] [Directory:/tmp/cpp-ethereum-20171112-28648-1fgx1py/_3rdParty/Hunter/toolchain]
------------------------------ WIKI -------------------------------
https://github.com/ruslo/hunter/wiki/error.no.toolchain.info
```

On https://github.com/ruslo/hunter/wiki/error.no.toolchain.info page:
```
Error may occurs for old version of compilers without #pragma message support.
E.g. minimal version of gcc is 4.4.7. In this case you need to update your compiler.
```

I'm not sure about brew part but I guess this is an instruction to update compiler (added to wiki):
* https://github.com/ethereum/homebrew-ethereum/issues/121#issuecomment-322513918
* https://github.com/ethereum/homebrew-ethereum/issues/116#issuecomment-308650103

**Comment by hacpai** [comment]
same issue...

**Comment by EralpB** [comment]
same
