### ISSUE TITLE
Installation OS-X 10.9.5

### ISSUE THREAD

**Issue by glambeth** [ethereum/homebrew-ethereum#13]
Hi, I'm having some problems with the installation. I'm not really sure what exactly to post, but if there's anything else I need to get some help just let me know! 

I'm running brew install ethereum and here's the output (i already ran brew tap ethereum/ethereum)

==> Installing ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/ethereum--git
==> Checking out branch master
==> Patching
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ethereum/0.7.14-49-5 -DCMAKE_
==> make
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/ethereum-EagFzG/CMakeFiles  70 71 72 73 74 75 76 77 78
[ 34%] Built target solidity
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/ethereum-EagFzG/CMakeFiles  54 55 56 57
[ 34%] Built target p2p
make: *** [all] Error 2

**Comment by caktux** [comment]
master branch of cpp-ethereum is broken, try with `--devel` meanwhile

**Comment by caktux** [comment]
Should be fine now, feel free to reopen if it's still failing
