### ISSUE TITLE
"util.go:45: exit status 2 exit status 1 make: *** [all] Error 1" when executing brew install ethereum on El Capitan

### ISSUE THREAD

**Issue by inkognitole** [ethereum/homebrew-ethereum#132]
Hello!

Geth does not really want to install itself on my El Capitan machine of a MacBook Pro.

This is the complete error message I receive when executing this command:
brew install ethereum

==> make all
Last 15 lines from /Users/olegb/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/elgamal
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/s2k
github.com/ethereum/go-ethereum/internal/cmdtest
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/packet
github.com/ethereum/go-ethereum/internal/guide
github.com/ethereum/go-ethereum/p2p/simulations/examples
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp
github.com/ethereum/go-ethereum/internal/build
github.com/ethereum/go-ethereum/swarm/testutil
github.com/ethereum/go-ethereum/whisper/shhclient
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/whisper/whisperv6
util.go:45: exit status 2
exit status 1
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
MAC: installation error for  brew install ethereum https://github.com/ethereum/homebrew-ethereum/issues/131
Install all go-ethereum executables https://github.com/ethereum/homebrew-ethereum/pull/114
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Unable to install go-ethereum  https://github.com/ethereum/homebrew-ethereum/issues/89
Error installing go-ethereum on Mac OS X https://github.com/ethereum/homebrew-ethereum/issues/117

typing geth in terminal afterwards produces:
-bash: geth: command not found

I habe Xcode, version 8.2.1 installed on the machine.

Please help!

**Comment by foobarfighter** [comment]
I had this problem too.  geth was failing to build because I had previously installed quickBlocks (https://github.com/Great-Hill-Corporation/quickBlocks).  The install had written a file at `/usr/local/include/Block.h` which was masking a CoreFoundation framework file.  I deleted `/usr/local/include/Block.h` and everything installed correctly after that.

**Comment by inkognitole** [comment]
That did not help.
I deleted Block.h without any substantial result!
The same error message!

**Comment by HOkn** [comment]
### Solved this by updating Mac OS 
Updated to High Sierra version 10.13.2 (17C88), with the Security Update 2017-002.

PC: MacBook Air (13-inch, Mid 2012)
Geth Version: 1.8.0-unstable
Git Commit: 908faf8cd715c873e4b5fdbb7af8d4f496702d84
Architecture: amd64
Protocol Versions: [63 62]
Go Version: go1.9.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.9.2/libexec

Error Status:
After cloning geth from github;
```
➜  go-ethereum git:(master) ✗ make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/Cellar/go/1.9.2/libexec/bin/go install -ldflags -X main.gitCommit=908faf8cd715c873e4b5fdbb7af8d4f496702d84 -s -v ./cmd/geth
github.com/ethereum/go-ethereum/consensus/ethash
# github.com/ethereum/go-ethereum/consensus/ethash
consensus/ethash/consensus.go:299:42: next declared and not used
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1
```
Solved:
```
➜  go-ethereum git:(master) ✗ make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/Cellar/go/1.9.2/libexec/bin/go install -ldflags -X main.gitCommit=908faf8cd715c873e4b5fdbb7af8d4f496702d84 -s -v ./cmd/geth
github.com/ethereum/go-ethereum/consensus/ethash
...
github.com/ethereum/go-ethereum/cmd/geth
Done building.
Run "/Users/HOkn/go-ethereum/build/bin/geth" to launch geth.
```

**Comment by inkognitole** [comment]
updating to High Sierra is not an option!

My MacBook is too old!

**Comment by foobarfighter** [comment]
Maybe you can post the most recent error that you're getting after deleting `Block.h`.  Hoping you figure this out because I understand the frustration.  I had a very similar problem.

**Comment by inkognitole** [comment]
The same error message!
the same content!

**Comment by kristenstarr** [comment]
I dug into this by cloning the repo locally and printing out the error messages that were returned in looking for GOPATH and VERSION settings, and the real error message was as follows:

```
> # github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
In file included from vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
/usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
typedef char                    io_string_t[512];
                                ^
```
This error came from line 45 of util.go, the same one referenced I believe in some of the comments above. (I added the log.Fatal(version), resulting in the above log message)

```
func VERSION() string {
        version, err := ioutil.ReadFile("VERSION")
        log.Fatal(version)
        if err != nil {
                log.Fatal(err)
        }
        return string(bytes.TrimSpace(version))
}
```

I found a solution that worked for me [here](https://github.com/Homebrew/legacy-homebrew/issues/32587#issuecomment-56769620).

Perhaps this is a one-off for me, as I've messed around with my Golang installations and such on my machine, but maybe it will help someone!

**Comment by Daiya-Mita** [comment]
When I reinstalled OS, I encountered the Error .
But after I installed "node" (<-my node version is v9.5.0), I successfully install ethereum!

**Comment by inkognitole** [comment]
What do you mean by "node"?

**Comment by Daiya-Mita** [comment]
Oh! sorry, node.js.
So I did `brew install nodenv` -> do well path -> `nodenv install 9.5.0` -> `nodenv global 9.5.0`

**Comment by inkognitole** [comment]
Sorry.
Could you do a step by step for a newbie?

So far I understood: brew install nodenv

It worked!

Daiya-Mita <notifications@github.com> schrieb am Di., 20. Feb. 2018 um
03:26 Uhr:

**Comment by Daiya-Mita** [comment]
Ok
step1: `brew install nodenv`
step2: `echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.bash_profile`
step3: `echo 'eval "$(nodenv init -)"' >> ~/.bash_profile`
step4:  close Terminal.app & open Terminal.app
step5: `nodenv install 9.5.0`
step6: `nodenv global 9.5.0`
and then, you could install ethereum !

**Comment by crazyyi** [comment]
@Daiya-Mita I followed all the steps and I still couldn't install ethereum.

**Comment by 12789** [comment]
I got the same issue.

`brew doctor`

and remove all Unexpected header files

`brew install ethereum`

Done.

It's work for me.

**Comment by stvenyin** [comment]
Yes!i'm always appear this problem,but i sovle it by go version
Download the archive and extract it into /usr/local, creating a Go tree in /usr/local/go. For example:

tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
(Typically these commands must be run as root or through sudo.)

Add /usr/local/go/bin to the PATH environment variable. You can do this by adding this line to your /etc/profile (for a system-wide installation) or $HOME/.profile:

export PATH=$PATH:/usr/local/go/bin

Thank you very much.

**Comment by stvenyin** [comment]
You can see Goole broswer detali link :https://tonybai.com/2017/07/14/some-changes-in-go-1-9/

Thank you.

**Comment by inkognitole** [comment]
This is a Linux step by step, isn't it?
Or can I apply the changes in Mac OS X terminal, too?

Am Di., 11. Dez. 2018 um 04:02 Uhr schrieb stvenyin <
notifications@github.com>:
