### ISSUE TITLE
 Unknown CMake command "eth_policy".

### ISSUE THREAD

**Issue by plash29** [ethereum/homebrew-ethereum#134]
$ cmake -G "Visual Studio 14 2015 Win64"
CMake Error at CMakeLists.txt:40 (include):
  include could not find load file:

    EthPolicy

CMake Error at CMakeLists.txt:41 (eth_policy):
  Unknown CMake command "eth_policy".

-- Configuring incomplete, errors occurred!

**Comment by axic** [comment]
Are you sure this is the correct repo for this issue? Please open it on the correct project, I assume it is cpp-ethereum?

**Comment by axic** [comment]
It should be opened in https://github.com/ethereum/cpp-ethereum.
