### ISSUE TITLE
ethereum/ethereum/cpp-ethereum 1.3.0 did not build

### ISSUE THREAD

**Issue by delosivan** [ethereum/homebrew-ethereum#138]
after inputing this code for CPU mining:

brew reinstall cpp-ethereum --with-gpu-mining --devel --successful --verbose --headless --build-from-source

I received the above error message:

Error: ethereum/ethereum/cpp-ethereum 1.3.0 did not build
Logs:
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/00.options.out
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/01.cmake.cc
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/01.cmake
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/02.make.cc
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/CMakeCache.txt
     /Users/ivandelossantos/Library/Logs/Homebrew/cpp-ethereum/02.make
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

I am reporting per instructions.

**Comment by chfast** [comment]
No ethminer here. Go to https://github.com/ethereum-mining/ethminer.
