### ISSUE TITLE
AlethZero build failed on Mac 10.9.5

### ISSUE THREAD

**Issue by ManfredKarrer** [ethereum/homebrew-ethereum#14]
I build following:
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS
Took ages and failed at the end :-(

Downloaded AlethZero bindary is crashing at startup. Mist binary opens but then it hangs and need to kill it.

...
==> Checking out revision b441bd3e8d8635e8220926486fe83370dbeb43c2
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/jsonrpc/0.3.2 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
  src/jsonrpccpp/CMakeLists.txt:55 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/jsonrpc-FzXDzL/CMakeFiles/CMakeOutput.log".

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

/tmp/jsonrpc-FzXDzL/CMakeFiles/CMakeOutput.log does not exist.

**Comment by caktux** [comment]
It's `jsonrpc` that is failing here, try `brew remove jsonrpc && brew install jsonrpc` then retry.
