### ISSUE TITLE
Install solidity failed

### ISSUE THREAD

**Issue by wlemuel** [ethereum/homebrew-ethereum#141]
==> Installing solidity from ethereum/ethereum
==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.20/solidity_0.4.20.tar.gz
Already downloaded: /Users/stevelemuel/Library/Caches/Homebrew/solidity-0.4.20.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/solidity/0.4.20 -DCMAKE_BUILD_TYPE=Re
==> make install
Last 15 lines from /Users/stevelemuel/Library/Logs/Homebrew/solidity/02.make:
make[1]: *** [CMakeFiles/jsoncpp-project.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Building CXX object libdevcore/CMakeFiles/devcore.dir/SwarmHash.cpp.o
cd /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore && /usr/local/bin/ccache /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/include -isystem /usr/local/include -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20  -std=c++11 -fpermissive -O3 -DNDEBUG   -fstack-protector-strong -Wimplicit-fallthrough -Wall -Wextra -Werror -Wno-unknown-pragmas -Wno-unused-function -Wno-dangling-else -o CMakeFiles/devcore.dir/SwarmHash.cpp.o -c /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore/SwarmHash.cpp
[  7%] Building CXX object libdevcore/CMakeFiles/devcore.dir/UTF8.cpp.o
cd /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore && /usr/local/bin/ccache /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/include -isystem /usr/local/include -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20  -std=c++11 -fpermissive -O3 -DNDEBUG   -fstack-protector-strong -Wimplicit-fallthrough -Wall -Wextra -Werror -Wno-unknown-pragmas -Wno-unused-function -Wno-dangling-else -o CMakeFiles/devcore.dir/UTF8.cpp.o -c /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore/UTF8.cpp
[  8%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Whiskers.cpp.o
cd /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore && /usr/local/bin/ccache /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/include -isystem /usr/local/include -I/tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20  -std=c++11 -fpermissive -O3 -DNDEBUG   -fstack-protector-strong -Wimplicit-fallthrough -Wall -Wextra -Werror -Wno-unknown-pragmas -Wno-unused-function -Wno-dangling-else -o CMakeFiles/devcore.dir/Whiskers.cpp.o -c /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore/Whiskers.cpp
[  8%] Linking CXX static library libdevcore.a
cd /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore && /usr/local/Cellar/cmake/3.10.2/bin/cmake -P CMakeFiles/devcore.dir/cmake_clean_target.cmake
cd /tmp/solidity-20180215-38155-1fn6042/solidity_0.4.20/libdevcore && /usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/devcore.dir/link.txt --verbose=1
/usr/bin/ar qc libdevcore.a  CMakeFiles/devcore.dir/CommonData.cpp.o CMakeFiles/devcore.dir/CommonIO.cpp.o CMakeFiles/devcore.dir/Exceptions.cpp.o CMakeFiles/devcore.dir/IndentedWriter.cpp.o CMakeFiles/devcore.dir/SHA3.cpp.o CMakeFiles/devcore.dir/StringUtils.cpp.o CMakeFiles/devcore.dir/SwarmHash.cpp.o CMakeFiles/devcore.dir/UTF8.cpp.o CMakeFiles/devcore.dir/Whiskers.cpp.o
/usr/bin/ranlib libdevcore.a
[  8%] Built target devcore
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

----------
OS: macOS 10.13.2  x86_64

**Comment by axic** [comment]
Can you please open this issue on the solidity repo (https://github.com/ethereum/solidity) and provide a non-truncated log?
