### ISSUE TITLE
Brew install ethereum not working for Mac OS X 10.13.3

### ISSUE THREAD

**Issue by kevinyang372** [ethereum/homebrew-ethereum#148]
==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/kevin/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.8.0
==> go env
==> make all
Last 15 lines from /Users/kevin/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/dashboard
github.com/ethereum/go-ethereum/whisper/whisperv5
github.com/ethereum/go-ethereum/whisper/whisperv6
github.com/ethereum/go-ethereum/eth/filters
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/light
github.com/ethereum/go-ethereum/core/vm/runtime
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/whisper/shhclient
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/miner
github.com/ethereum/go-ethereum/eth/tracers
util.go:45: exit status 2
exit status 1
make: *** [all] Error 1

My homebrew is the latest version and GO is 1.10

**Comment by Brenndoerfer** [comment]
Same issue

**Comment by BennIThink** [comment]
Same issue here

**Comment by StDogbert** [comment]
+1

**Comment by aristeidys** [comment]
same issue here

**Comment by hermartin1994** [comment]
+1

**Comment by andrewmckinnon2** [comment]
+1

**Comment by alexkarasyov** [comment]
+1

**Comment by RobinJayaswal** [comment]
Discussion of problem and workaround here: https://github.com/ethereum/go-ethereum/issues/16118

**Comment by trvstan** [comment]
+1

**Comment by qasimsoomro** [comment]
+1

**Comment by spkinger** [comment]
+1

**Comment by ccwukong** [comment]
+1

**Comment by karalabe** [comment]
This was an issue with the filesystem notification library (i.e. Go 1.10 changed some compiler options that caused build failures). Geth 1.8.1 was just release that fixes this issue too among a couple other tiny thing. Please try gain with the new version.
