### ISSUE TITLE
Brew install ethereum not working for Mac OS X 10.13.3

### ISSUE THREAD

**Issue by BennIThink** [ethereum/homebrew-ethereum#149]
==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/kevin/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.8.0
==> go env
==> make all
Last 15 lines from /Users/kevin/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/dashboard
github.com/ethereum/go-ethereum/whisper/whisperv5
github.com/ethereum/go-ethereum/whisper/whisperv6
github.com/ethereum/go-ethereum/eth/filters
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/light
github.com/ethereum/go-ethereum/core/vm/runtime
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/whisper/shhclient
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/miner
github.com/ethereum/go-ethereum/eth/tracers
util.go:45: exit status 2
exit status 1
make: *** [all] Error 1

Homebrew and Go versions:
HOMEBREW_VERSION: 1.5.4
go version go1.10

**Comment by StDogbert** [comment]
+1

**Comment by BrettKoenig** [comment]
+1

**Comment by kevinyang372** [comment]
+1

**Comment by hermartin1994** [comment]
+1

**Comment by andrewmckinnon2** [comment]
+1

**Comment by pezzullig** [comment]
+1

**Comment by alexkarasyov** [comment]
+1

**Comment by aristeidys** [comment]
+1

**Comment by RobinJayaswal** [comment]
Discussion of problem and workaround here: ethereum/go-ethereum#16118

**Comment by axic** [comment]
Duplicate of #148.

**Comment by atifaslem** [comment]
+1
