### ISSUE TITLE
Mist won't install with homebrew

### ISSUE THREAD

**Issue by joeykrug** [ethereum/homebrew-ethereum#15]
I get the following error:

MacBook-Pro:augur-serpent joeykrug2$ brew install go-ethereum
 ==> Installing go-ethereum from caktux/homebrew-ethereum
 ==> Cloning https://github.com/ethereum/go-ethereum.git
 Updating /Library/Caches/Homebrew/go-ethereum--git
 ==> Checking out branch master
 ==> go env
 ==> go get -v -u -d github.com/ethereum/go-ethereum/ethereum
 package github.com/ethereum/go-ethereum/ethereum
 imports github.com/ethereum/go-ethereum/ethereum
 imports github.com/ethereum/go-ethereum/ethereum: cannot find package "github.com/ethereum/go-ethereum/ethereum" in any of:
 /usr/local/opt/go/libexec/src/github.com/ethereum/go-ethereum/ethereum (from $GOROOT)
 /private/tmp/go-ethereum-fH5uch/src/github.com/ethereum/go-ethereum/ethereum (from $GOPATH)

**Comment by joeykrug** [comment]
Seems reinstalling boost fixed this error - on a side note, --devel doesn't work for go-ethereum on brew, although the master version does install

**Comment by caktux** [comment]
mist should work on develop, make sure you `brew switch qt5 5.4.0`
