### ISSUE TITLE
failed onstallation on mac os x 10.13.3

### ISSUE THREAD

**Issue by zdary** [ethereum/homebrew-ethereum#152]
I tried to install ethereum from brew but it failed. see below.

`🍺  /usr/local/Cellar/miniupnpc/2.0.20180222: 22 files, 183.2KB
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --headless option so it will be ignored!
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --with-gpu-mining option so it will be ignored!
==> Installing ethereum/ethereum/cpp-ethereum --devel
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/i303703/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 609, done.
remote: Compressing objects: 100% (584/584), done.
remote: Total 609 (delta 80), reused 152 (delta 10), pack-reused 0
Receiving objects: 100% (609/609), 1.18 MiB | 605.00 KiB/s, done.
Resolving deltas: 100% (80/80), done.
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_M
Last 15 lines from /Users/i303703/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180314-13829-enyxdn/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
Error While Installation of cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/133
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mining on MacBookPro issue with cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/111
cpp-ethereum OSX build failed: Install clang 4+ from Homebrew https://github.com/ethereum/homebrew-ethereum/issues/127
Mac OS X 10.12.5 install error for cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/120
cpp-ethereum issue on mac: CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message): https://github.com/ethereum/homebrew-ethereum/issues/129
C02VL1XDHTDD:~ i303703$`

**Comment by LiweiDong** [comment]
same issues

**Comment by lynnchai** [comment]
same issue.

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180316-43257-bnzrdd/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
Error While Installation of cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/133
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mining on MacBookPro issue with cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/111
cpp-ethereum OSX build failed: Install clang 4+ from Homebrew https://github.com/ethereum/homebrew-ethereum/issues/127
Mac OS X 10.12.5 install error for cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/120
cpp-ethereum issue on mac: CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message): https://github.com/ethereum/homebrew-ethereum/issues/129
