### ISSUE TITLE
no reason to maintain jsonrpc4 any more

### ISSUE THREAD

**Issue by debris** [ethereum/homebrew-ethereum#16]
we don't need to maintain jsonrpc4 anymore
jsonrpc4 is finally available in homebrew.

```
brew install libjson-rpc-cpp
```

so when we finally [move to version 4](https://github.com/ethereum/cpp-ethereum/pull/970), we will use default homebrew package

**Comment by caktux** [comment]
Will update when that gets merged, we'll still need `jsonrpc.rb` until develop gets merged
