### ISSUE TITLE
Error Installing C++ for Ethereum on Mac

### ISSUE THREAD

**Issue by BlakeChaseley** [ethereum/homebrew-ethereum#161]
Mac OS High Sierra Version: 10.13.3 (17D102)

```
Chases-MacBook-Pro-2017:~ chase$ brew tap ethereum/ethereum
Chases-MacBook-Pro-2017:~ chase$ brew install cpp-ethereum
brew linkapps cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/chase/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 614, done.
remote: Compressing objects: 100% (590/590), done.
remote: Total 614 (delta 80), reused 156 (delta 9), pack-reused 0
Receiving objects: 100% (614/614), 1.20 MiB | 4.57 MiB/s, done.
Resolving deltas: 100% (80/80), done.
==> Checking out branch develop
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
Last 15 lines from /Users/chase/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180330-41832-enzfhg/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

Chases-MacBook-Pro-2017:~ chase$ brew linkapps cpp-ethereum
Warning: Calling 'brew linkapps' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cmd/linkapps.rb:18:in `linkapps'

Error: No such keg: /usr/local/Cellar/cpp-ethereum
```

**Comment by axic** [comment]
This seems to be an issue between hunter and homebrew, I think @ruslo and @chfast try to sort this one out.

**Comment by ruslo** [comment]
Last error in Hunter logs is not relevant, the first error message is important. As far as I understand it's:
* https://github.com/ruslo/hunter/wiki/error.no.toolchain.info

Reason:
* https://discourse.brew.sh/t/c-homebrew-compiler-suppress-pragma-messages/1893

**Comment by axic** [comment]
@ruslo I think you should open an issue on https://github.com/Homebrew/brew. @MikeMcQuaid (and team) was very quick at responding to questions.

**Comment by MikeMcQuaid** [comment]
Please don't due to:

> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/ethereum/homebrew-ethereum/issues

**Comment by axic** [comment]
@MikeMcQuaid I am a bit confused.

This problem doesn't seem to be related to cpp-ethereum, since this minimal example (https://github.com/hunter-packages/toolchain-info-mini) has the same effect. It is a problem between Hunter and Homebrew, which @ruslo, the author of Hunter, tries to figure out and solve.

**Comment by MikeMcQuaid** [comment]
If there's a minimal reproducible case that could be reported to Homebrew. In this case: it already was in our Discourse.

**Comment by ilovezfs** [comment]
You can hack around it with
```
ENV["CC"] = "/usr/bin/clang"
ENV["CXX"] = "/usr/bin/clang++"
```
but a proper solution is needed in hunter not brew, I think.

Also, hunter seems to be grabbing `boost` but might as well `depends_on "boost"` if possible.

**Comment by ruslo** [comment]
> You can hack around it with

It's the same as forcing compiler in toolchain, already mentioned here:
* https://github.com/ruslo/hunter/wiki/error.no.toolchain.info

> but a proper solution is needed in hunter not brew, I think.

This is a questionable statement. Also I did find the reason of why messages are suppressed, see note about HOMEBREW_CCCFG environment variable.

> hunter seems to be grabbing boost but might as well depends_on "boost" if possible

You should either disable Hunter and use brew to manage dependencies or use Hunter to download boost and the rest of dependencies. "Injecting" dependencies from outside into Hunter is not supported by design because it conflicts with reproducibility feature.

**Comment by ilovezfs** [comment]
@ruslo it even occurs if I pass `--env=std`.

**Comment by ruslo** [comment]
> it even occurs if I pass --env=std

@ilovezfs Sorry, I don't have enough experience with brew to understand what it means :)

**Comment by ilovezfs** [comment]
@ruslo it means I passed `brew install --env=std ...` to use "stdenv" instead of "superenv" so there's significantly less magic during the build, which may make the specific issue easier to track down.

**Comment by axic** [comment]
@ruslo I am curious if you get it to work with these instructions? :)

**Comment by ruslo** [comment]
> I am curious if you get it to work with these instructions?

@axic You mean with `brew install --env=std`? No, the error is the same.

**Comment by jeffs** [comment]
Is this the same issue?  Work-arounds welcome.

```sh
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Installing dependencies for ethereum/ethereum/cpp-ethereum: cmake, gperftools, snappy, leveldb
==> Installing ethereum/ethereum/cpp-ethereum dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.11.2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.11.2.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
/usr/local/Cellar/cmake/3.11.2: 2,363 files, 32.7MB
==> Installing ethereum/ethereum/cpp-ethereum dependency: gperftools
==> Downloading https://homebrew.bintray.com/bottles/gperftools-2.7.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gperftools-2.7.high_sierra.bottle.tar.gz
/usr/local/Cellar/gperftools/2.7: 103 files, 4.3MB
==> Installing ethereum/ethereum/cpp-ethereum dependency: snappy
==> Downloading https://homebrew.bintray.com/bottles/snappy-1.1.7_1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring snappy-1.1.7_1.high_sierra.bottle.tar.gz
/usr/local/Cellar/snappy/1.1.7_1: 18 files, 118KB
==> Installing ethereum/ethereum/cpp-ethereum dependency: leveldb
==> Downloading https://homebrew.bintray.com/bottles/leveldb-1.20_2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring leveldb-1.20_2.high_sierra.bottle.tar.gz
/usr/local/Cellar/leveldb/1.20_2: 26 files, 1.2MB
==> Installing ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/jeff/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 613, done.
remote: Compressing objects: 100% (576/576), done.
remote: Total 613 (delta 84), reused 167 (delta 22), pack-reused 0
Receiving objects: 100% (613/613), 1.19 MiB | 8.32 MiB/s, done.
Resolving deltas: 100% (84/84), done.
==> Checking out branch develop
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp
Last 15 lines from /Users/jeff/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.73/5cd594b/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:87 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180524-72063-1yj2pi/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

```

**Comment by jgelsey** [comment]
I have the same problem.

**Comment by damofthemoon** [comment]
+1 here

**Comment by ShanghaiTimes** [comment]
https://github.com/ethereum/homebrew-ethereum/issues

Same here.

**Comment by ShanghaiTimes** [comment]
Ok,  had a look at the odd fixes here and there, but like others, one problem leads to another.
What is the command line I use to install cpp-ethereum with hunter disabled. Nothing I do seems to affect it.

**Comment by ShanghaiTimes** [comment]
Is anybody working on this yet?

**Comment by rgaufman** [comment]
Anyone have a workaround?

**Comment by k06a** [comment]
Having the same issue, need a workaround!

**Comment by alailsonribeiro** [comment]
Having the same issue, need a workaround!

**Comment by alailsonribeiro** [comment]
```

MacBook-Pro-de-Alailson:ethereum alailsonribeiro$ brew install --env=std cpp-ethereum
Updating Homebrew...
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/aleth.git
Updating /Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out tag v1.4.0rc5
HEAD is now at 9bc368d Aleth 1.4.0rc5
HEAD is now at 9bc368d Aleth 1.4.0rc5
Entering 'evmc'
Entering 'evmjit'
Synchronizing submodule url for 'evmc'
Entering 'evmjit/evmc'
Entering 'hera'
Synchronizing submodule url for 'cmake/cable'
Synchronizing submodule url for 'evm2wasm'
Synchronizing submodule url for 'evmc'
Entering 'hera/cmake/cable'
Entering 'hera/evm2wasm'
Entering 'hera/evmc'
Entering 'test/jsontests'
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/evmc
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/evmjit
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/evmjit/evmc
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/hera
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/hera/cmake/cable
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/hera/evm2wasm
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/hera/evmc
/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git/test/jsontests
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.4.0rc5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWO
Last 15 lines from /Users/alailsonribeiro/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:71 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180830-18435-42jnpa/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

```

**Comment by axic** [comment]
@ruslo @chfast any new ideas how to fix/solve this?

**Comment by kaustubh-seachange** [comment]
Facing the same error with Aleth version 1.5.2, any updates on this.

'==> Checking out tag v1.5.2
HEAD is now at 2a2e584 Aleth 1.5.2
Submodule 'cable' (https://github.com/ethereum/cable) registered for path 'cmake/cable'
Submodule 'evmc' (https://github.com/ethereum/evmc) registered for path 'evmc'
Submodule 'test/jsontests' (https://github.com/ethereum/tests.git) registered for path 'test/jsontests'
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/cmake/cable'...
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/evmc'...
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/test/jsontests'...
Submodule path 'cmake/cable': checked out 'cd585c5a70374f335336cd3240fcd22f64d794ed'
Submodule path 'evmc': checked out '354ba6f540655649e081fb455e21998186bf5576'
Submodule path 'test/jsontests': checked out '4cfaa3e600f45d34bc00d88a4b142d2f27762912'
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/cmake/cable
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/evmc
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/test/jsontests
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
Last 15 lines from /Users/kaustubh/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:110 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:135 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:65 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20190307-31013-1km0jj0/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues'

**Comment by kaustubh-seachange** [comment]
Facing the same problem while installing Aleth 1.5.2, Any updates on how to resolve this issue.

> ==> Checking out tag v1.5.2
HEAD is now at 2a2e584 Aleth 1.5.2
Submodule 'cable' (https://github.com/ethereum/cable) registered for path 'cmake/cable'
Submodule 'evmc' (https://github.com/ethereum/evmc) registered for path 'evmc'
Submodule 'test/jsontests' (https://github.com/ethereum/tests.git) registered for path 'test/jsontests'
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/cmake/cable'...
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/evmc'...
Cloning into '/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/test/jsontests'...
Submodule path 'cmake/cable': checked out 'cd585c5a70374f335336cd3240fcd22f64d794ed'
Submodule path 'evmc': checked out '354ba6f540655649e081fb455e21998186bf5576'
Submodule path 'test/jsontests': checked out '4cfaa3e600f45d34bc00d88a4b142d2f27762912'
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/cmake/cable
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/evmc
/Users/kaustubh/Library/Caches/Homebrew/cpp-ethereum--git/test/jsontests
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
Last 15 lines from /Users/kaustubh/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:110 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:135 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:65 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20190307-31013-1km0jj0/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

**Comment by mgogel** [comment]
Was there a resolve? I still can't install cpp-ethereum and it's been a year since the issue was opened.

**Comment by chfast** [comment]
This is not going to be fixed. We don't have anyone who is able to maintain homebrew. But even if there was someone, homebrew is incompatible with Aleth's build system, so it requires substantial amount of work.

**Comment by mgogel** [comment]
straight forward and good answer! thank you for the update.

**Comment by chfast** [comment]
To be clear, we publish macOS binaries: https://github.com/ethereum/aleth/releases/tag/v1.5.2

Should be easy as downloading and unpacking binaries. This is not as convenient as homebrew, but much cheaper for us to support.

**Comment by ChrisChinchilla** [comment]
I _may_ take a look at some point, as having some success with other Homebrew issues (here and with other projects), but this particular issue may be beyond me…
