### ISSUE TITLE
Make a Error when installing Solidity

### ISSUE THREAD

**Issue by todamoon1** [ethereum/homebrew-ethereum#178]
system :mac os x yosemite 10.10.5

```
==> Installing solidity from ethereum/ethereum
==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.24/solidity_0.4.24.tar.gz
Already downloaded: /Users/nick/Library/Caches/Homebrew/solidity-0.4.24.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/solidity/0
==> make install
Last 15 lines from /Users/nick/Library/Logs/Homebrew/solidity/02.make:
/tmp/solidity-20180719-67773-uhmx22/solidity_0.4.24/libevmasm/SourceLocation.h:48:2: note: candidate constructor not viable: no known conversion from 'TypedName' (aka 'dev::solidity::assembly::TypedName') to 'const dev::SourceLocation &' for 1st argument
        SourceLocation(SourceLocation const&) = default;
        ^
1 error generated.
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/__/libjulia/optimiser/FullInliner.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Linking CXX static library liblll.a
cd /tmp/solidity-20180719-67773-uhmx22/solidity_0.4.24/liblll && /usr/local/Cellar/cmake/3.12.0/bin/cmake -P CMakeFiles/lll.dir/cmake_clean_target.cmake
cd /tmp/solidity-20180719-67773-uhmx22/solidity_0.4.24/liblll && /usr/local/Cellar/cmake/3.12.0/bin/cmake -E cmake_link_script CMakeFiles/lll.dir/link.txt --verbose=1
/usr/bin/ar qc liblll.a  CMakeFiles/lll.dir/CodeFragment.cpp.o CMakeFiles/lll.dir/Compiler.cpp.o CMakeFiles/lll.dir/CompilerState.cpp.o CMakeFiles/lll.dir/Parser.cpp.o
/usr/bin/ranlib liblll.a
[ 40%] Built target lll
make: *** [all] Error 2
```

**Comment by anakornk** [comment]
Ran into similar problem, anyone know how to fix this?
```
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/solidity/0.4.25 -DCMAKE_BUILD_TYPE=Release
==> make install
Last 15 lines from /Users/anakornk/Library/Logs/Homebrew/solidity/02.make:
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:792:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    basic_string(size_type __n, _CharT __c, const _Allocator& __a);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:796:5: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
    basic_string(const basic_string& __str, size_type __pos,
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:793:5: note: candidate constructor not viable: requires at least 3 arguments, but 1 was provided
    basic_string(const basic_string& __str, size_type __pos, size_type __n,
    ^
2 errors generated.
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Getting issues while installing solidity https://github.com/ethereum/homebrew-ethereum/issues/177
Make a Error when installing Solidity https://github.com/ethereum/homebrew-ethereum/issues/178

```

**Comment by kwladyka** [comment]
The same issue what @anakornk has with macOS Mojave, Version 10.14.1. Fresh installed system.

**Comment by gilgameshskytrooper** [comment]
bump

**Comment by kerzhner** [comment]
Same issue as @anakornk on macOS 10.13.6 with xcode 10B61.

**Comment by barca** [comment]
is there anything close to a fix? it seems like nothing I'm able to do is working.

**Comment by FateZero666** [comment]
I'm running OSM10.14,Xcode version10.1.  what should i do?

 brew install solidity
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
beast                      mongodb                    node-build

==> Installing solidity from ethereum/ethereum
==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.25/s
Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/f121c86691c385dc6276695ad897006d4592c2310dd6bbf15960c9ccfaea259a--solidity_0.4.25.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make install
Last 15 lines from /Users/saber/Library/Logs/Homebrew/solidity/02.make:
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:792:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    basic_string(size_type __n, _CharT __c, const _Allocator& __a);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:796:5: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
    basic_string(const basic_string& __str, size_type __pos,
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:793:5: note: candidate constructor not viable: requires at least 3 arguments, but 1 was provided
    basic_string(const basic_string& __str, size_type __pos, size_type __n,
    ^
2 errors generated.
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Getting issues while installing solidity https://github.com/ethereum/homebrew-ethereum/issues/177
Make a Error when installing Solidity https://github.com/ethereum/homebrew-ethereum/issues/178

**Comment by FateZero666** [comment]
brew install solidity

2 errors generated.
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Getting issues while installing solidity https://github.com/ethereum/homebrew-ethereum/issues/177
Make a Error when installing Solidity https://github.com/ethereum/homebrew-ethereum/issues/178

**Comment by axic** [comment]
Without proper logs, just these small snippets, it is kind of impossible to identify the problem.

The original report from @todamoon1 is on ancient macOS system, while the others seems to be different issues.

**Comment by axic** [comment]
@todamoon1's original issue refers to a piece of code which has been rewritten.

Everybody else, please open a distinct issue. Also note this from the README:
> **Important note: reporting issues with any of these brews should be done at their respective repositories (Go client, C++ client and Solidity).**

**Comment by mlong168** [comment]
The same error with homebrew and solidity_0.5.3. Installs fine from source ./scripts/build.sh 

=> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/solidity/0.5.3 -DCMAKE_BUILD_TYPE=Rel
==> make install
Last 15 lines from /Users/mlong/Library/Logs/Homebrew/solidity/02.make:
      typeinfo for langutil::UnimplementedFeatureError in CommandLineInterface.cpp.o
      typeinfo for langutil::Error in CommandLineInterface.cpp.o
      ...
  "vtable for dev::solidity::ASTPrinter", referenced from:
      dev::solidity::CommandLineInterface::handleAst(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in CommandLineInterface.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for dev::solidity::ASTJsonConverter", referenced from:
      dev::solidity::CommandLineInterface::handleCombinedJSON() in CommandLineInterface.cpp.o
      dev::solidity::CommandLineInterface::handleAst(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in CommandLineInterface.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [solc/solc] Error 1
make[1]: *** [solc/CMakeFiles/solc.dir/all] Error 2
make: *** [all] Error 2
