### ISSUE TITLE
cpp-ethereum: QT error building natspec

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/homebrew-ethereum#20]
```
$ brew reinstall --build-from-source cpp-ethereum --devel

==> Reinstalling cpp-ethereum with --with-debug, --with-gui
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.9.13-60-9 -DCMAKE_BUILD_TYPE=Re
==> make
Generating moc_SortFilterProxyModel.cpp
Generating moc_Web3Server.cpp
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum20150422-44947-12ozoky/CMakeFiles
[ 15%] Built target mix_automoc
make: *** [all] Error 2
```

```
In file included from /usr/local/opt/qt5/lib/QtQml.framework/Headers/qjsengine.h:42:
/usr/local/opt/qt5/lib/QtQml.framework/Headers/qjsvalue.h:132:21: error: expected ';' at end of declaration list
    QJSValue(void *) Q_DECL_EQ_DELETE;
                    ^
6 warnings and 1 error generated.
make[2]: *** [libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o] Error 1
make[1]: *** [libnatspec/CMakeFiles/natspec.dir/all] Error 2
```

full logs: https://gist.github.com/anonymous/325f80c95612a7f4f36a

**Comment by debris** [comment]
did you have this issues with older versions of cpp-etheruem? We haven't changed natspec stuff for a while... I see that you have cmake 3.2.2. I will check if this is related.

**Comment by jorisbontje** [comment]
@debris my previous (successful) cpp-ethereum install was on April 10th:
```
$ ./eth --version
eth version 0.9.6
eth network protocol version: 60
Client database version: 12041
Build: linux/clang/int/Debug
```

With cmake 3.2.1 I have the same issue:
https://gist.github.com/anonymous/5c44cb80846a880f0978

**Comment by jorisbontje** [comment]
This is affected by `--with-gui`; without that installation works fine.

**Comment by caktux** [comment]
Still occurring?

**Comment by ghaskins** [comment]
I just saw a similar error following the standard brew installation procedure on OSX 10.8.5:

==> Installing cpp-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 971, done.
remote: Compressing objects: 100% (854/854), done.
remote: Total 971 (delta 145), reused 427 (delta 64), pack-reused 0
Receiving objects: 100% (971/971), 2.42 MiB | 0 bytes/s, done.
Resolving deltas: 100% (145/145), done.
Checking connectivity... done.
==> Checking out branch master
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.8.2-54- -
==> make
Generating moc_StatusPane.cpp
Generating moc_Web3Server.cpp
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum20150616-38684-17r3kdj/CMakeFiles 
[  4%] Built target mix_automoc
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

greg:~ ghaskins$ cmake --version
cmake version 3.2.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
greg:~ ghaskins$ uname -a
Darwin greg.haskins.net 12.6.0 Darwin Kernel Version 12.6.0: Wed Mar 18 16:23:48 PDT 2015; root:xnu-2050.48.19~1/RELEASE_X86_64 x86_64

**Comment by debris** [comment]
please reopen, if it still occurs
