### ISSUE TITLE
Building ethereum, not working

### ISSUE THREAD

**Issue by jonathan-s** [ethereum/homebrew-ethereum#21]
This is the error I get

    ==> Checking out branch master
    ==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.8.2-54-5 -DCMAKE_BUILD_T
    ==> make
    /usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum-EVkUS9/CMakeFiles  41 42
    /usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum-EVkUS9/CMakeFiles  58 59 60 61 62
    [ 32%] [ 32%] Built target lll
    Built target p2p
    make: *** [all] Error 2

**Comment by caktux** [comment]
```
brew update
```
Feel free to reopen with more debug info if it's still occurring :)
