### ISSUE TITLE
Please update readme.md

### ISSUE THREAD

**Issue by KenKappler** [ethereum/homebrew-ethereum#23]
minor fix to naming:

==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/ethereum--git
fatal: reference is not a tree: <latest commit hash>
Error: Failed to download resource "ethereum"
Failure while executing: git checkout -q -f

Either try brew fetch cpp-ethereum --devel or simply delete the cache with 
rm -rf /Library/Caches/Homebrew/ethereum--git

should be:

==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/**cpp-ethereum--git**
fatal: reference is not a tree: <latest commit hash>
Error: Failed to download resource "**cpp-ethereum**"
Failure while executing: git checkout -q -f

Either try brew fetch cpp-ethereum --devel or simply delete the cache with 
rm -rf /Library/Caches/Homebrew/**cpp-ethereum--git**

**Comment by caktux** [comment]
As a side note, the location of the checkout is chosen by brew itself from the name of the formula. Make sure you `brew update` to get the `cpp-ethereum` formula, since the `ethereum` one has been for go-ethereum for a while already (go-ethereum -> ethereum, ethereum -> cpp-ethereum)
