### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by fractastical** [ethereum/homebrew-ethereum#29]
`brew install cpp-ethereum`

Ends with 

/usr/local/Cellar/cmake/3.2.3/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum20150723-9978-fiwhf5/CMakeFiles  47 48
[ 39%] Built target lll
make: *** [all] Error 2

on OS X 10.9.4

**Comment by fractastical** [comment]
`==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR
  CMakeLists.txt:346 (include)`

Tried another few times. Ends with

**Comment by aakilfernandes** [comment]
+1

**Comment by aakilfernandes** [comment]
Was able to fix this with `brew install qt5` and `brew link qt5 --overwrite`. Turns out I had some wrong version of qt5 installed and that was breaking things.

For those having similar issues, I suggest running `brew install cpp-ethereum` with the `--debug` flag then reading the log right before the fail. Then make sure the relevant homebrew packages are installed AND linked.

**Comment by jooray** [comment]
```
brew install cpp-ethereum --with-gui
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.9.41 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -
==> make
Generating moc_InjectTransactions.cpp
Generating moc_Whisper.cpp
Generating moc_WhisperPeers.cpp
[ 18%] Built target AlethZero_automoc
make: *** [all] Error 2
```

Is this the same issue or a different one? Updated brew, tried with several versions. Even tried the llvm suggestion and reinstall of qt5 with --overwrite linking as suggested above.

**Comment by m-vdb** [comment]
+1 (Mac 10.10.5)

**Comment by m-vdb** [comment]
I just followed the troubleshooting instructions and used the `--verbose` flag, here is the output:
```
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
CMake Error at /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
```

Found this https://trac.macports.org/ticket/44210 on the matter

**Comment by sacketty** [comment]
+1 (10.10.5)
see [https://gist.github.com/anonymous/4c891bbb6853b8bcc3b4](https://gist.github.com/anonymous/4c891bbb6853b8bcc3b4)

**Comment by ethg** [comment]
+1 (10.11)
No permission errors.
I followed the troubleshooting instructions, checked for common issues, ran `brew install llvm --HEAD --with-clang` has mentioned in the Warning, but I still have this message after running `brew install cpp-ethereum`: `make: *** [all] Error 2`

[https://gist.github.com/c38db6fc91d5e32932ec](https://gist.github.com/c38db6fc91d5e32932ec)

**Comment by andreagalvagni** [comment]
+1 (10.11.1)

**Comment by jmadan** [comment]
followed below steps after reading above comments

> brew install qt5
> brew link qt5 --overwrite
> brew install llvm --HEAD --with-clang
> brew install cpp-ethereum

still it ends up throwing the following error
[ 61%] Built target solidity
make: *** [all] Error 2

Is there a way to install cpp-ethereum on OSX10.11.1?

**Comment by Richardxlin** [comment]
+1 Mac (10.11) 
[ 61%] Linking CXX executable testweb3core
cd /tmp/cpp-ethereum20151031-52316-1f68o3a/libweb3core/test && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/testweb3core.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testweb3core.dir/overlaydb.cpp.o CMakeFiles/testweb3core.dir/test.cpp.o CMakeFiles/testweb3core.dir/libdevcore/Base36.cpp.o CMakeFiles/testweb3core.dir/libdevcore/CommonJS.cpp.o CMakeFiles/testweb3core.dir/libdevcore/core.cpp.o CMakeFiles/testweb3core.dir/libdevcore/FixedHash.cpp.o CMakeFiles/testweb3core.dir/libdevcore/RangeMask.cpp.o CMakeFiles/testweb3core.dir/libdevcore/rlp.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/AES.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/crypto.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/hexPrefix.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/MemTrie.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/SecretStore.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/trie.cpp.o CMakeFiles/testweb3core.dir/libp2p/capability.cpp.o CMakeFiles/testweb3core.dir/libp2p/net.cpp.o CMakeFiles/testweb3core.dir/libp2p/peer.cpp.o CMakeFiles/testweb3core.dir/libp2p/rlpx.cpp.o  -o testweb3core  /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libminiupnpc.dylib ../libp2p/libp2p.dylib /usr/local/lib/libboost_unit_test_framework-mt.a /usr/local/lib/libboost_regex-mt.a ../libdevcrypto/libdevcrypto.dylib ../libdevcore/libdevcore.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread ../../webthree-helpers/utils/libscrypt/libscrypt.dylib /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libgmp.dylib /usr/local/lib/libminiupnpc.dylib 
[ 61%] Built target testweb3core
make: *** [all] Error 2
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make

**Comment by hynese** [comment]
+1 

I even tried:

`brew unlink qt5`
`brew link --force qt5`

Which didn't work either...

**Comment by MeLoco1** [comment]
I have the same error 

[ 61%] Linking CXX shared library libsolidity.dylib
cd /tmp/cpp-ethereum20151108-55148-19qa5nx/solidity/libsolidity && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/solidity.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++  -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -DSTATICLIB -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o libsolidity.dylib -install_name /tmp/cpp-ethereum20151108-55148-19qa5nx/solidity/libsolidity/libsolidity.dylib CMakeFiles/solidity.dir/analysis/ConstantEvaluator.cpp.o CMakeFiles/solidity.dir/analysis/DeclarationContainer.cpp.o CMakeFiles/solidity.dir/analysis/DocStringAnalyser.cpp.o CMakeFiles/solidity.dir/analysis/GlobalContext.cpp.o CMakeFiles/solidity.dir/analysis/NameAndTypeResolver.cpp.o CMakeFiles/solidity.dir/analysis/ReferencesResolver.cpp.o CMakeFiles/solidity.dir/analysis/TypeChecker.cpp.o CMakeFiles/solidity.dir/ast/AST.cpp.o CMakeFiles/solidity.dir/ast/ASTAnnotations.cpp.o CMakeFiles/solidity.dir/ast/ASTJsonConverter.cpp.o CMakeFiles/solidity.dir/ast/ASTPrinter.cpp.o CMakeFiles/solidity.dir/ast/ASTUtils.cpp.o CMakeFiles/solidity.dir/ast/Types.cpp.o CMakeFiles/solidity.dir/codegen/ArrayUtils.cpp.o CMakeFiles/solidity.dir/codegen/Compiler.cpp.o CMakeFiles/solidity.dir/codegen/CompilerContext.cpp.o CMakeFiles/solidity.dir/codegen/CompilerUtils.cpp.o CMakeFiles/solidity.dir/codegen/ExpressionCompiler.cpp.o CMakeFiles/solidity.dir/codegen/LValue.cpp.o CMakeFiles/solidity.dir/formal/Why3Translator.cpp.o CMakeFiles/solidity.dir/interface/CompilerStack.cpp.o CMakeFiles/solidity.dir/interface/Exceptions.cpp.o CMakeFiles/solidity.dir/interface/GasEstimator.cpp.o CMakeFiles/solidity.dir/interface/InterfaceHandler.cpp.o CMakeFiles/solidity.dir/interface/SourceReferenceFormatter.cpp.o CMakeFiles/solidity.dir/interface/Version.cpp.o CMakeFiles/solidity.dir/parsing/DocStringParser.cpp.o CMakeFiles/solidity.dir/parsing/Parser.cpp.o CMakeFiles/solidity.dir/parsing/Scanner.cpp.o CMakeFiles/solidity.dir/parsing/Token.cpp.o /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread ../../libethereum/libevmasm/libevmasm.dylib ../../libethereum/libevmcore/libevmcore.dylib ../../libweb3core/libdevcore/libdevcore.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread
[ 61%] Built target solidity
make: *** [all] Error 2

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: fda36921cb2d2d7875a8c2e0bc44715477ecf5e0
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.1
CLT: N/A
GCC-4.2: build 0
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_31

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/curl:/usr/local/opt/v8-315:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/argtable/lib/pkgconfig:/usr/local/opt/jsoncpp/lib/pkgconfig:/usr/local/opt/libmicrohttpd/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.11
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/cryptopp/bin:/usr/local/opt/miniupnpc/bin:/usr/local/opt/leveldb/bin:/usr/local/opt/curl/bin:/usr/local/opt/libjson-rpc-cpp/bin:/usr/local/opt/v8-315/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by maco144** [comment]
+1 10.9

**Comment by maco144** [comment]
Is this an issue with my C compiler? I have 6.2 xcode which is most up to date for mavericks.

clang: error: unknown argument: '-fstack-protector-strong'
make[2]: *** [libethereum/libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o] Error 1
make[1]: *** [libethereum/libnatspec/CMakeFiles/natspec.dir/all] Error 2
[  4%] Built target secp256k1
[  4%] Built target scrypt
make: *** [all] Error 2
==> Formula
Tap: ethereum/homebrew-ethereum
Path: /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 2e6eec26cf30cd92ddda6f27ef03bb08a9feb8c3
Last commit: 82 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: N/A
Clang: 6.0 build 600
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-462
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/curl:/usr/local/opt/v8-315:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/argtable/lib/pkgconfig:/usr/local/opt/jsoncpp/lib/pkgconfig:/usr/local/opt/libmicrohttpd/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/cryptopp/bin:/usr/local/opt/miniupnpc/bin:/usr/local/opt/leveldb/bin:/usr/local/opt/curl/bin:/usr/local/opt/libjson-rpc-cpp/bin:/usr/local/opt/v8-315/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by iPadGuy** [comment]
+1 OSX 10.9.5 Mavericks

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117? Thanks!

Everybody else - Lots of love has gone into OS X builds in the past week or so, and we believe everything is nice and healthy now.   See https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X.    Please can you log new issues if you still hit anything?   Thanks!

**Comment by bobsummerwill** [comment]
This one can be closed too, @caktux.   Thanks!
