### ISSUE TITLE
request: solidity compiler (solc) as stand-alone formula

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/homebrew-ethereum#31]

**Comment by greggdourgarian** [comment]
yeah running in circles on mac install...currently says error EVMJIT needs latest llvm and run `brew install llvm --HEAD --with-clang` error 

but that brew takes an hour to run and still get the same error

**Comment by RCasatta** [comment]
confirming @greggdourgarian issue

**Comment by greggdourgarian** [comment]
hi...i eventually got this by upgrading my mac to Yosemite and installing the latest, released xcode

**Comment by RCasatta** [comment]
got Yosemite 10.10.5 (14F27) and no available updates of xcode.
`install llvm --HEAD --with-clang` works
but then
`brew reinstall cpp-ethereum --devel`
ask again the latest llvm version

**Comment by greggdourgarian** [comment]
hi RC.  You've followed the process for mac install here?  https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS

**Comment by RCasatta** [comment]
i launched the brew commands
`brew reinstall cpp-ethereum --devel`
`brew reinstall cpp-ethereum --devel  --build-from-source`

then i followed the "build from source" from your link
after:
`LLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake cmake ..`

i got always more or less the same error:
```
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:10 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!
```

**Comment by greggdourgarian** [comment]
Hi...trying to remember other things I did.  

One was to upgrade 'bew' and run 'brew doctor' and then follow its instructions for fixing errors it found.   

Also, I used SUDO in running virtually all the commands in the process.

Hope this helps.

**Comment by RCasatta** [comment]
Thanks @greggdourgarian however it looks the command I needed was
`git clone https://github.com/ethereum/cpp-ethereum-cmake`
taken from
https://github.com/ethereum/cpp-ethereum/issues/2904
I updated the wiki page for MacOs.
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS

**Comment by caktux** [comment]
This went from a feature request to a general support thread regarding LLVM... closing in favor of #42
