### ISSUE TITLE
fatal error: 'gmp.h' file not found (Mac OS X Mavericks)

### ISSUE THREAD

**Issue by matthewtoast** [ethereum/homebrew-ethereum#32]
I've actually resolved this issue myself, but I'm reporting it for posterity since this is the repo that is recommended for troubleshooting when running the Geth command-line installer. The resolution is below.

I try to install Geth Frontier on Mac OS X 10.9 (Mavericks).

    $ bash <(curl https://install-geth.ethereum.org -L)

Eventually the process fails with this message:

    ==> Installing ethereum/ethereum/ethereum
    ==> Cloning https://github.com/ethereum/go-ethereum.git
    Cloning into '/Library/Caches/Homebrew/ethereum--git'...
    remote: Counting objects: 2120, done.
    remote: Compressing objects: 100% (1376/1376), done.
    remote: Total 2120 (delta 800), reused 1474 (delta 652), pack-reused 0
    Receiving objects: 100% (2120/2120), 8.85 MiB | 2.32 MiB/s, done.
    Resolving deltas: 100% (800/800), done.
    Checking connectivity... done.
    ==> Checking out branch master
    ==> go env
    ==> go build -v ./src/github.com/ethereum/go-ethereum/cmd/evm
    github.com/syndtr/goleveldb/leveldb/table
    github.com/ethereum/go-ethereum/logger
    github.com/syndtr/goleveldb/leveldb
    github.com/ethereum/go-ethereum/metrics
    github.com/ethereum/go-ethereum/ethdb
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/ethereum/homebrew-ethereum/issues

    $ brew linkapps ethereum
    Error: No such keg: /usr/local/Cellar/ethereum

    ==> Verifying installation
     ✘  Geth is missing

    ==> Installation failed

So I try to install Ethereum directly in verbose mode:

    $ brew install ethereum -v

This command gives the following message:

    ==> Installing ethereum from ethereum/homebrew-ethereum
    ==> Cloning https://github.com/ethereum/go-ethereum.git
    git --git-dir /Library/Caches/Homebrew/ethereum--git/.git status -s
    Updating /Library/Caches/Homebrew/ethereum--git
    git config remote.origin.url https://github.com/ethereum/go-ethereum.git
    git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
    git fetch origin
    git checkout -f master --
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    git reset --hard origin/master
    HEAD is now at fc79d32 Merge pull request #1552 from ethereum/revert-1551-remove-p224
    git submodule foreach --recursive git submodule sync
    git submodule update --init --recursive
    ==> Checking out branch master
    ==> go env
    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/private/tmp/ethereum20150801-71743-jrr93e/src/github.com/ethereum/go-ethereum/Godeps/_workspace:/private/tmp/ethereum20150801-71743-jrr93e"
    GORACE=""
    GOROOT="/usr/local/opt/go/libexec"
    GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"
    ==> go build -v ./src/github.com/ethereum/go-ethereum/cmd/evm
    github.com/ethereum/go-ethereum/rlp
    github.com/kardianos/osext
    code.google.com/p/go-uuid/uuid
    github.com/ethereum/go-ethereum/crypto/ecies
    github.com/ethereum/go-ethereum/crypto/sha3
    golang.org/x/crypto/pbkdf2
    golang.org/x/crypto/ripemd160
    github.com/ethereum/go-ethereum/logger/glog
    golang.org/x/crypto/scrypt
    github.com/rcrowley/go-metrics
    github.com/syndtr/goleveldb/leveldb/util
    github.com/ethereum/go-ethereum/crypto/randentropy
    github.com/syndtr/goleveldb/leveldb/comparer
    github.com/ethereum/go-ethereum/crypto/secp256k1
    github.com/syndtr/gosnappy/snappy
    github.com/ethereum/go-ethereum/params
    github.com/ethereum/go-ethereum/event
    github.com/syndtr/goleveldb/leveldb/cache
    github.com/syndtr/goleveldb/leveldb/storage
    github.com/syndtr/goleveldb/leveldb/filter
    github.com/hashicorp/golang-lru
    gopkg.in/fatih/set.v0
    # github.com/ethereum/go-ethereum/crypto/secp256k1
    In file included from src/github.com/ethereum/go-ethereum/crypto/secp256k1/secp256.go:34:
    In file included from ././secp256k1/src/secp256k1.c:12:
    In file included from ././secp256k1/src/num_impl.h:14:
    In file included from ././secp256k1/src/num.h:17:
    ././secp256k1/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
    #include <gmp.h>
             ^
    1 error generated.
    github.com/syndtr/goleveldb/leveldb/opt
    github.com/ethereum/go-ethereum/common
    github.com/syndtr/goleveldb/leveldb/errors
    github.com/syndtr/goleveldb/leveldb/iterator
    github.com/syndtr/goleveldb/leveldb/journal
    github.com/syndtr/goleveldb/leveldb/memdb
    github.com/syndtr/goleveldb/leveldb/table
    github.com/ethereum/go-ethereum/logger
    github.com/ethereum/go-ethereum/metrics
    github.com/syndtr/goleveldb/leveldb
    github.com/ethereum/go-ethereum/ethdb
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    ==> Formula
    Tap: ethereum/homebrew-ethereum
    Path: /usr/local/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb
    ==> Configuration
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew.git
    HEAD: a9a6e1e7b62dbf4c0d1c5b5d00fdd2527a5a2ff6
    Last commit: 83 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: 8-core 64-bit ivybridge
    OS X: 10.9.3-x86_64
    Xcode: 5.1.1
    CLT: 5.1.0.0.1.1396320587
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    GCC-4.2: build 0
    Clang: 5.1 build 503
    X11: 2.7.4 => /opt/X11
    System Ruby: 2.0.0-p451
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /Users/matthew/.rvm/rubies/ruby-1.9.3-p194/bin/ruby
    Java: N/A
    ==> ENV
    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    MAKEFLAGS: -j8
    CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local
    CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
    ACLOCAL_PATH: /usr/local/share/aclocal
    PATH: /private/tmp/ethereum20150801-71743-jrr93e/src/github.com/ethereum/go-ethereum/Godeps/_workspace:/private/tmp/ethereum20150801-71743-jrr93e/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/go/bin:/usr/local/opt/mercurial/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

    Error: ethereum/ethereum/ethereum 1.0.0 did not build
    Logs:
         /Users/matthew/Library/Logs/Homebrew/ethereum/01.go
         /Users/matthew/Library/Logs/Homebrew/ethereum/02.go
         /Users/matthew/Library/Logs/Homebrew/ethereum/02.go.cc

It looks like the problem might be with this line:

    ././secp256k1/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
    #include <gmp.h>

**Comment by matthewtoast** [comment]
I Google around and eventually find these pages from people who have hit the same issue:

* https://github.com/wanderer/secp256k1-node/issues/9
* https://blog.ethereum.org/2015/07/27/final-steps/
* https://github.com/ethereum/go-ethereum/issues/224
* https://github.com/ethereum/go-ethereum/issues/56

**The solution seems to be to uninstall-then-reinstall `gmp`.**

OK, let's try to uninstall `gmp` and then try again.

    $ brew uninstall gmp

That looks OK, let's try Geth install again.

    $ bash <(curl https://install-geth.ethereum.org -L)

Success! That did it.

    ==> Verifying installation
     ✓  Found geth: /usr/local/bin/geth
    Geth
    Version: 1.0.0
    Protocol Versions: [61 60]
    Network Id: 1
    Go Version: go1.4.2
    OS: darwin
    GOPATH=
    GOROOT=/usr/local/Cellar/go/1.4.2/libexec

    ==> Installation successful!
    ==> Next steps
    ==> Run `geth help` to get started.

**Comment by ramvi** [comment]
This doesn't work for me. Same error. Still there after reinstall

**Comment by alanwunsche** [comment]
My attempt:

brew install ethereal -v

contains the following error which prevents the 1.3.1 build:

In file included from ././libsecp256k1/src/secp256k1.c:11:
././libsecp256k1/src/util.h:14:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>

**Comment by matthewtoast** [comment]
@alanwunsche  You may want to try opening a new issue for that error since it's different than the one I reported here. (`gmp.h` vs. `stdlib.h`)

**Comment by alanwunsche** [comment]
Thanks. I posted at forum.Ethereum.org under the geth category

On Nov 5, 2015, at 8:07 AM, Matthew Trost <notifications@github.com> wrote:

@alanwunsche You may want to try opening a new issue for that error since it's different than the one I reported here. (gmp.h vs. stdlib.h)
