### ISSUE TITLE
Configuring incomplete. EthPolicy missing?

### ISSUE THREAD

**Issue by ajunge** [ethereum/homebrew-ethereum#33]
brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch master
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.9.41 -DCMAKE_BUIL
  CMakeLists.txt:8 (project)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum20150826-555-wm8gev/CMakeFiles/CMakeOutput.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

**Comment by m-vdb** [comment]
I was able to fix it on mac osx (see https://github.com/ethereum/homebrew-ethereum/issues/29)

**Comment by m-vdb** [comment]
arf, actually I didn't fix it... I found the commit that included the EthPolicy: https://github.com/ethereum/cpp-ethereum/commit/5fe91b75c0170ccffa5f4c231d01a71bae378647

@arkpar do you have any idea why installing `cpp-ethereum` with homebrew like the following:
```bash
brew install cpp-ethereum --devel --with-gui
```
fails? I tried with `--success` or other options without any result. The complete output with verbose:
```
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.9.41-61 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release -DEVMJIT=0 -DFATDB=1 -DGUI=1
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:10 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!
```

I'm kinda stuck here (the only reason I wanna install with devel is that I want to get the Mix app)

**Comment by m-vdb** [comment]
sorry for the spam, `--successful` works

**Comment by debris** [comment]
this issue is already resolved
