### ISSUE TITLE
Can´t install ethereum with GUI

### ISSUE THREAD

**Issue by avolution** [ethereum/homebrew-ethereum#37]
mac:~ macuser$ brew update
Updated Homebrew from a2a72b4d to 1a2e7fc0.
==> Updated Formulae
ace    davix
mac:~ macuser$ brew install cpp-ethereum --with-gui
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch master
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.9.41 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release -DEVMJIT=0 -DFATDB=1 -DGUI=1

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum20150915-73927-10fbm01/CMakeFiles/CMakeOutput.log".
See also "/tmp/cpp-ethereum20150915-73927-10fbm01/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

mac:~ macuser$ brew install llvm --HEAD --with-clang
Warning: llvm-HEAD already installed
mac:~ macuser$ 

The Files /tmp/cpp-ethereum20150915-73927-10fbm01/CMakeFiles/CMakeOutput.log and /tmp/cpp-ethereum20150915-73927-10fbm01/CMakeFiles/CMakeError.log does not exist.

**Comment by debris** [comment]
please reopen if it still occurs
