### ISSUE TITLE
No such file or directory - test/testeth

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/homebrew-ethereum#38]
I believe its related to this line

https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb#L99

**Comment by aakilfernandes** [comment]
Error: No such file or directory - test/testeth
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Homebrew/extend/pathname.rb:56:in `install_p'
/usr/local/Library/Homebrew/extend/pathname.rb:35:in `block in install'
/usr/local/Library/Homebrew/extend/pathname.rb:16:in `each'
/usr/local/Library/Homebrew/extend/pathname.rb:16:in `install'
/usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb:99:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:848:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1386:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1378:in `stage'
/usr/local/Library/Homebrew/formula.rb:844:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:176:in `<main>'

**Comment by Mattivc** [comment]
I get the exact same error:
```
rew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Downloading http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/18/artifact/webthree-umbrel

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "cpp-ethereum"
Download failed: http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/18/artifact/webthree-umbrella/build/cpp-ethereum-1.0rc2.yosemite.bottle.18.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/c
==> make
==> make install
Error: No such file or directory - test/testeth
```

**Comment by aakilfernandes** [comment]
I was able to get this older by reverting to an older version. My guess is that this formula expects geth 1.2 while homebrew installs geth 1.1.3

    cd /usr/local/Library/Taps/ethereum/homebrew-ethereum/1
    git pull --depth=50
    git checkout dcc07a44844508fdd3fea2a3a3a5fb913e75b9e9
    brew install cpp-ethereum

**Comment by debris** [comment]
should be fixed in next build
