### ISSUE TITLE
Error on "brew install cpp-ethereum"

### ISSUE THREAD

**Issue by benkobler** [ethereum/homebrew-ethereum#39]
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Installing cpp-ethereum dependency: homebrew/versions/v8-315
==> Downloading https://homebrew.bintray.com/bottles/v8-315-3.15.11.18.yosemite.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "v8-315"
Download failed: https://homebrew.bintray.com/bottles/v8-315-3.15.11.18.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/v8/v8-git-mirror/archive/3.15.11.18.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 389c03f67731874342486536bd231c43281fe43d05001664000abd3ac48fd9cf
Actual: 93a4945a550e5718d474113d9769a3c010ba21e3764df8f22932903cd106314d
Archive: /Library/Caches/Homebrew/v8-315-3.15.11.18.tar.gz
To retry an incomplete download, remove the file above.

**Comment by fogr4** [comment]
This particular error disappeared after running brew update and brew doctor
