### ISSUE TITLE
Wrong version of libminiupnpc

### ISSUE THREAD

**Issue by wid** [ethereum/homebrew-ethereum#44]
Hi, 

I manage to make eth working but when I update brew it has installed the following version of miniupnpc:
```
~ $ ls -l /usr/local/Cellar/miniupnpc/1.9.20151008/lib/
total 232
-r--r--r--  1 wid  admin  47800 Oct 26 13:02 libminiupnpc.15.dylib
-r--r--r--  1 wid  admin  61488 Oct 21 15:48 libminiupnpc.a
lrwxr-xr-x  1 wid  admin     21 Oct 21 15:48 libminiupnpc.dylib -> libminiupnpc.15.dylib
```
It looks like eth needs another version to work:
```
~ $ eth
dyld: Library not loaded: /usr/local/lib/libminiupnpc.13.dylib
  Referenced from: /usr/local/bin/eth
  Reason: image not found
```

**Comment by debris** [comment]
@LefterisJP can you manually reinstall libminiupnpc on buildbot? Homebrew recently started hosting bottles on their own dependency server and their rebuilt a lot of bottles without upgrading bottle version (whereas inner version changed).

**Comment by LefterisJP** [comment]
@debris you mean the Jenkins macosx slave?

**Comment by debris** [comment]
yes

**Comment by debris** [comment]
fixed in latest bottle
