### ISSUE TITLE
Bottle for El Captain of cpp-ethereum

### ISSUE THREAD

**Issue by debris** [ethereum/homebrew-ethereum#45]
We should setup jenkins slave on `el captain` to build it.

**Comment by bobsummerwill** [comment]
If this was referring to geth, that appears to have happened.
If this was referring to eth, it appears not specifically to be necessary.

Please can we close this, @chriseth?   CC @debris.

**Comment by bobsummerwill** [comment]
This one can be closed too, @caktux.   Thanks!

**Comment by caktux** [comment]
That's still missing for cpp-ethereum, let's leave it opened until it is.

**Comment by bobsummerwill** [comment]
It is?   Is "brew install cpp-ethereum" using a Yosemite bottle then?   And it "just works"?

**Comment by caktux** [comment]
It doesn't use the Yosemite bottle if you're on El Capitan, no. So everyone on El Capitan ends up having to build the whole thing.

**Comment by bobsummerwill** [comment]
Oh right - I see.

I am on El Capitan, and was thinking "Wow - this kinda sucks".   So Yosemite users just get prebuilt binaries, but we haven't been producing prebuilt binaries for El Capitan yet.

Are the Yosemite ones generated automatically with each run of the automation step?   At the same point at which https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb is getting auto-updated?

**Comment by bobsummerwill** [comment]
What is the work required to add a cpp-ethereum bottle for El Capitan, @caktux?
Is this purely a matter of hardware?   That we only have a single Mac doing the work, and it's a Yosemite box?
Or something else?    Anything I can do to help close it off?   Thanks!

**Comment by caktux** [comment]
@bobsummerwill Yes the Yosemite bottles are built on every run, but that's being done by the cpp Jenkins setup which I know nothing about, and not the https://builds.ethereum.org buildbot. And yes, it's a matter of hardware, they'll need Mac on El Capitan to build those. Hope that clears it up :)

**Comment by bobsummerwill** [comment]
Now covered by https://github.com/ethereum/webthree-umbrella/issues/185.
