### ISSUE TITLE
Install cpp-ethereum fail on Mac OSX 10.11

### ISSUE THREAD

**Issue by ThomRoux** [ethereum/homebrew-ethereum#47]
Same final make issue : 

`[ 93%] Built target testeth
make: *** [all] Error 2`

`Brew doctor` says nothing, and `brew info cpp-ethereum` says the following : 

`ethereum/ethereum/cpp-ethereum: stable 1.0rc2, devel 1.0rc2
https://github.com/ethereum/webthree-umbrella
/usr/local/Cellar/cpp-ethereum/1.0rc2 (4 files, 16K) *
  Built from source
From: https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb
==> Dependencies
Build: cmake ✔
Required: boost ✔, readline ✔, cryptopp ✔, miniupnpc ✔, leveldb ✔, gmp ✔, curl ✔, libjson-rpc-cpp ✔, homebrew/versions/v8-315 ✔`

I enclosed the log from `brew install cpp-ethereum --with-gpu-mining --devel --headless --build-from-source --verbose --debug`, but same issue with `brew install cpp-ethereum`only.

brew install cpp-ethereum --with-gpu-mining --devel --headless --build-from-source --verbose --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cryptopp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/miniupnpc.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/leveldb.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/snappy.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/curl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libjson-rpc-cpp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/argtable.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jsoncpp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libmicrohttpd.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/v8-315.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cryptopp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/miniupnpc.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/leveldb.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/snappy.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/curl.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libjson-rpc-cpp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/argtable.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jsoncpp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libmicrohttpd.rb
/usr/local/Library/Homebrew/build.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/v8-315.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/git.rb
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
git config remote.origin.url https://github.com/ethereum/webthree-umbrella.git
git config remote.origin.fetch +refs/heads/develop:refs/remotes/origin/develop
git fetch origin
==> Checking out branch develop
git checkout -f develop --
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.
git reset --hard origin/develop
HEAD is now at 6ce9d20 updated submodules
git submodule foreach --recursive git submodule sync
Entering 'alethzero'
Entering 'libethereum'
Entering 'libweb3core'
Entering 'mix'
Entering 'solidity'
Entering 'web3.js'
Entering 'webthree'
Entering 'webthree-helpers'
git submodule update --init --recursive
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.0rc2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release -DEVMJIT=0 -DGUI=0
-- The C compiler identification is AppleClang 7.0.0.7000176
-- The CXX compiler identification is AppleClang 7.0.0.7000176
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- boost headers: /usr/local/include
-- boost lib   : /usr/local/lib/libboost_thread-mt.a;/usr/local/lib/libboost_date_time-mt.a;/usr/local/lib/libboost_system-mt.a;/usr/local/lib/libboost_regex-mt.a;/usr/local/lib/libboost_chrono-mt.a;/usr/local/lib/libboost_filesystem-mt.a;/usr/local/lib/libboost_unit_test_framework-mt.a;/usr/local/lib/libboost_program_options-mt.a;/usr/local/lib/libboost_random-mt.a

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Found gmp: /usr/local/include  
-- Gmp headers: /usr/local/include
-- Gmp lib   : /usr/local/lib/libgmp.dylib

------------------------------------------------------------------------
-- Configuring dev
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        ON
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              ON
-- TOOLS            Build tools                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Found jsoncpp: /usr/local/include  
-- JsonCpp headers: /usr/local/include
-- JsonCpp lib   : /usr/local/lib/libjsoncpp.dylib
-- Found leveldb: /usr/local/include  
-- LevelDB headers: /usr/local/include
-- LevelDB lib   : /usr/local/lib/libleveldb.dylib
-- Found CryptoPP: /usr/local/include (found suitable exact version "5.6.2") 
-- CryptoPP headers: /usr/local/include
-- CryptoPP lib   : /usr/local/lib/libcryptopp.a
-- Found miniupnpc: /usr/local/include  
-- miniupnpc headers: /usr/local/include
-- miniupnpc lib   : /usr/local/lib/libminiupnpc.dylib
./overlaydb.cpp./test.cpp./libdevcore/./Base36.cpp./libdevcore/./CommonJS.cpp./libdevcore/./core.cpp./libdevcore/./FixedHash.cpp./libdevcore/./RangeMask.cpp./libdevcore/./rlp.cpp./libdevcrypto/./AES.cpp./libdevcrypto/./crypto.cpp./libdevcrypto/./hexPrefix.cpp./libdevcrypto/./MemTrie.cpp./libdevcrypto/./SecretStore.cpp./libdevcrypto/./trie.cpp./libp2p/./capability.cpp./libp2p/./net.cpp./libp2p/./peer.cpp./libp2p/./rlpx.cpp

------------------------------------------------------------------------
-- Configuring ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- OLYMPIC          Default to the Olympic network           OFF
-- PARANOID         -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              ON
-- ETHASHCL         Build OpenCL components                  ON
-- EVMJIT           Build LLVM-based JIT EVM                 OFF
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework  
-- OpenCL headers: /System/Library/Frameworks/OpenCL.framework
-- OpenCL lib   : /System/Library/Frameworks/OpenCL.framework
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- Found json_rpc_cpp: /usr/local/include (found suitable version "0.5.0", minimum required is "0.4") 
-- json-rpc-cpp headers: /usr/local/include
-- json-rpc-cpp lib   : /usr/local/lib/libjsonrpccpp-common.dylib;/usr/local/lib/libjsonrpccpp-server.dylib;/usr/local/lib/libjsonrpccpp-client.dylib
-- Found CURL: /usr/local/opt/curl/include  
-- curl headers: /usr/local/opt/curl/include
-- curl lib   : /usr/local/opt/curl/lib/libcurl.dylib
-- Found mhd: /usr/local/include  
-- microhttpd headers: /usr/local/include
-- microhttpd lib   : /usr/local/lib/libmicrohttpd.dylib
-- jsonrpcstub location    : /usr/local/bin/jsonrpcstub
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest

------------------------------------------------------------------------
-- Configuring webthree
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- c8 headers: /usr/local/opt/v8-315/include
-- c8 lib   : /usr/local/opt/v8-315/lib/libv8.dylib
-- Found readline: /usr/local/Cellar/readline/6.3.8/include  
-- readline headers: /usr/local/Cellar/readline/6.3.8/include
-- readline lib   : /usr/local/Cellar/readline/6.3.8/lib/libreadline.dylib

------------------------------------------------------------------------
-- Configuring solidity
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- solidity headers: /tmp/cpp-ethereum20151103-65952-1wb0cme/solidity
-- solidity lib   : solidity
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/cpp-ethereum20151103-65952-1wb0cme
==> make

(skipping purposedly some stuff with no errors)

[ 87%] Building CXX object webthree/libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/LevelDB.cpp.o
cd /tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc && /usr/local/Library/ENV/4.3/clang++   -DETH_ETHASHCL -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_JSCONSOLE -DETH_JSONRPC -DETH_MINIUPNPC -DETH_TRUE -Dweb3jsonrpc_EXPORTS -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE -fPIC -isystem /usr/local/include -I/tmp/cpp-ethereum20151103-65952-1wb0cme/libethereum -I/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree -isystem /tmp/cpp-ethereum20151103-65952-1wb0cme/webthree-helpers/utils -I/tmp/cpp-ethereum20151103-65952-1wb0cme/libweb3core -I/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/include -I/tmp/cpp-ethereum20151103-65952-1wb0cme -I/tmp/cpp-ethereum20151103-65952-1wb0cme/include -I/tmp/cpp-ethereum20151103-65952-1wb0cme/gen -I/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/gen -I/tmp/cpp-ethereum20151103-65952-1wb0cme/libethereum/include -isystem /usr/local/opt/curl/include -I/tmp/cpp-ethereum20151103-65952-1wb0cme/libethereum/libethash-cl    -o CMakeFiles/web3jsonrpc.dir/LevelDB.cpp.o -c /tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/LevelDB.cpp
In file included from /tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/Eth.cpp:39:
In file included from /tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/Eth.h:32:
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:563:1: error: 'virtual' can only appear on non-static member functions
virtual Json::Value eth_getUncleCountByBlockHash(const std::string& param1) = 0;
^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:563:21: error: illegal initializer (only variables can be initialized)
virtual Json::Value eth_getUncleCountByBlockHash(const std::string& param1) = 0;
                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:564:17: error: 'virtual' can only appear on non-static member functions
                virtual Json::Value eth_getUncleCountByBlockNumber(const std::string& param1) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:564:37: error: illegal initializer (only variables can be initialized)
                virtual Json::Value eth_getUncleCountByBlockNumber(const std::string& param1) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:565:17: error: 'virtual' can only appear on non-static member functions
                virtual std::string eth_getCode(const std::string& param1, const std::string& param2) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:565:37: error: illegal initializer (only variables can be initialized)
                virtual std::string eth_getCode(const std::string& param1, const std::string& param2) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:566:17: error: 'virtual' can only appear on non-static member functions
                virtual std::string eth_sendTransaction(const Json::Value& param1) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:566:37: error: illegal initializer (only variables can be initialized)
                virtual std::string eth_sendTransaction(const Json::Value& param1) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:567:17: error: 'virtual' can only appear on non-static member functions
                virtual std::string eth_call(const Json::Value& param1, const std::string& param2) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:567:37: error: illegal initializer (only variables can be initialized)
                virtual std::string eth_call(const Json::Value& param1, const std::string& param2) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:568:17: error: 'virtual' can only appear on non-static member functions
                virtual bool eth_flush() = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:568:30: error: illegal initializer (only variables can be initialized)
                virtual bool eth_flush() = 0;
                             ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:569:17: error: 'virtual' can only appear on non-static member functions
                virtual Json::Value eth_getBlockByHash(const std::string& param1, bool param2) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:569:37: error: illegal initializer (only variables can be initialized)
                virtual Json::Value eth_getBlockByHash(const std::string& param1, bool param2) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:570:17: error: 'virtual' can only appear on non-static member functions
                virtual Json::Value eth_getBlockByNumber(const std::string& param1, bool param2) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:570:37: error: illegal initializer (only variables can be initialized)
                virtual Json::Value eth_getBlockByNumber(const std::string& param1, bool param2) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:571:17: error: 'virtual' can only appear on non-static member functions
                virtual Json::Value eth_getTransactionByHash(const std::string& param1) = 0;
                ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:571:37: error: illegal initializer (only variables can be initialized)
                virtual Json::Value eth_getTransactionByHash(const std::string& param1) = 0;
                                    ^
/tmp/cpp-ethereum20151103-65952-1wb0cme/webthree/libweb3jsonrpc/EthFace.h:572:17: error: 'virtual' can only appear on non-static member functions
                virtual Json::Value eth_getTransactionByBlockHashAndIndex(const std::string& param1, const std::string& param2) = 0;
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [webthree/libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/Eth.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

(skipping again some stuff with no errors)

[ 93%] Linking CXX executable testeth
cd /tmp/cpp-ethereum20151103-65952-1wb0cme/libethereum/test && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/testeth.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testeth.dir/BlockChainHelper.cpp.o CMakeFiles/testeth.dir/boostTest.cpp.o CMakeFiles/testeth.dir/Stats.cpp.o CMakeFiles/testeth.dir/TestHelper.cpp.o CMakeFiles/testeth.dir/TestUtils.cpp.o CMakeFiles/testeth.dir/fuzzTesting/createRandomTest.cpp.o CMakeFiles/testeth.dir/fuzzTesting/fuzzHelper.cpp.o CMakeFiles/testeth.dir/libethcore/commonjs.cpp.o CMakeFiles/testeth.dir/libethcore/dagger.cpp.o CMakeFiles/testeth.dir/libethcore/difficulty.cpp.o CMakeFiles/testeth.dir/libethcore/icap.cpp.o CMakeFiles/testeth.dir/libethcore/keymanager.cpp.o CMakeFiles/testeth.dir/libethereum/AccountDiff.cpp.o CMakeFiles/testeth.dir/libethereum/blockchain.cpp.o CMakeFiles/testeth.dir/libethereum/blockqueue.cpp.o CMakeFiles/testeth.dir/libethereum/ClientBase.cpp.o CMakeFiles/testeth.dir/libethereum/gaspricer.cpp.o CMakeFiles/testeth.dir/libethereum/genesis.cpp.o CMakeFiles/testeth.dir/libethereum/state.cpp.o CMakeFiles/testeth.dir/libethereum/stateOriginal.cpp.o CMakeFiles/testeth.dir/libethereum/Transaction.cpp.o CMakeFiles/testeth.dir/libethereum/transactionqueue.cpp.o CMakeFiles/testeth.dir/libethereum/transactionTests.cpp.o CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o CMakeFiles/testeth.dir/libevm/vm.cpp.o CMakeFiles/testeth.dir/libnatspec/natspec.cpp.o CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o  -o testeth  /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libcryptopp.a -framework OpenCL /usr/local/lib/libminiupnpc.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libmicrohttpd.dylib /usr/local/lib/libjsonrpccpp-common.dylib /usr/local/lib/libjsonrpccpp-server.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libjsonrpccpp-common.dylib /usr/local/lib/libjsonrpccpp-client.dylib /usr/local/opt/curl/lib/libcurl.dylib /usr/local/lib/libboost_regex-mt.a ../libtestutils/libtestutils.dylib /usr/local/lib/libboost_unit_test_framework-mt.a ../libethereum/libethereum.dylib ../libevm/libevm.dylib ../libethcore/libethcore.dylib ../libethash-cl/libethash-cl.dylib ../libethash/libethash.dylib -framework OpenCL ../liblll/liblll.dylib ../libevmasm/libevmasm.dylib ../libevmcore/libevmcore.dylib ../../libweb3core/libp2p/libp2p.dylib ../../libweb3core/libdevcrypto/libdevcrypto.dylib ../../libweb3core/libdevcore/libdevcore.dylib ../../webthree-helpers/utils/libscrypt/libscrypt.dylib /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libgmp.dylib /usr/local/lib/libminiupnpc.dylib /usr/local/lib/libmicrohttpd.dylib /usr/local/lib/libjsonrpccpp-common.dylib /usr/local/lib/libjsonrpccpp-server.dylib /usr/local/lib/libjsonrpccpp-common.dylib /usr/local/lib/libjsonrpccpp-server.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread /usr/local/lib/libjsonrpccpp-client.dylib /usr/local/opt/curl/lib/libcurl.dylib /usr/local/lib/libboost_regex-mt.a 
[ 93%] Built target testeth
make: *** [all] Error 2
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:

**Comment by debris** [comment]
should be fixed on latest develop
