### ISSUE TITLE
cryptopp was updated to 5.6.3, breaks cpp-etherum build

### ISSUE THREAD

**Issue by rweichler** [ethereum/homebrew-ethereum#49]
```
CMake Error at webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP: Found unsuitable version "5.6.3", but required is
  exact version "5.6.2" (found /usr/local/include)
```

Was fixed by reverting [homebrew/cryptopp](https://github.com/Homebrew/homebrew/blob/12f42a6761cb29ed3c9715fe2cbccff02bdc448f/Library/Formula/cryptopp.rb) (to 12f42a6761cb29ed3c9715fe2cbccff02bdc448f) and installing it from there.

Will need to add cryptopp-5.6.2 to a tap, or have cpp-etherum support cryptopp-5.6.3.

**Comment by jimchang7** [comment]
Yeah, I think does it make more sense that cpp-etherum support cryptopp-5.6.3? 5.6.2 was release on 02/20/2013 -- 2 years ago

**Comment by Darwinium** [comment]
How to install cryptopp 5.6.2 version? Please help)
I've tried, but don't know how to install another version of brew formula

**Comment by dreid93** [comment]
@Darwinium check out the instructions here : https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

**Comment by bobsummerwill** [comment]
Hey guys!
@rweichler @Darwinium @jimchang7 :-)

This has been addressed now.   Please can you retry?

If you are lucky then doing `brew reinstall` on cpp-ethereum will do the job, or you may need to `brew update` and `brew reinstall` on all the dependencies too.

Please could you try and report back?   Thanks!

+ @area

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117?  Thanks!

**Comment by bobsummerwill** [comment]
This one can be closed too, @caktux.   Thanks!
