### ISSUE TITLE
verify_app issue for Qt apps (absolute paths for dylibs)

### ISSUE THREAD

**Issue by fossilet** [ethereum/homebrew-ethereum#52]
With `brew install --verbose --with-gui cpp-ethereum`, `qt5` is not installing as a dependency. I have to manually install `qt5` to proceed QT compiling errors. Is there some problem with the formula?

**Comment by area** [comment]
I think this is due to the warning that you get when installing QT5 that it conflicts with QT4, and therefore the formula is keg-only.

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117?  Thanks!    Or you close it yourself, @fossilet?   Thanks!

**Comment by bobsummerwill** [comment]
Thanks, @fossilet!

**Comment by fossilet** [comment]
Thank you too, @bobsummerwill .

**Comment by bobsummerwill** [comment]
I've come to conclusion that there *is* an issue with the Formula.

The conditional dependency which it declares onto Qt5 simply **does not work**, from what I can see in my painful explorations over the past few days.

https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb#L34

Any input on what the hell might be going wrong here, @caktux?

See also https://github.com/ethereum/homebrew-ethereum/issues/53.

**Comment by bobsummerwill** [comment]
Just looking back at https://github.com/ethereum/homebrew-ethereum/issues/46#issuecomment-172156506 too.    We need to make the --with-d-bus change you suggested for sure, @caktux, but I think we also need to drop the conditional (or rework it, if you have any suggestion on how?).   I'll make a PR.

**Comment by bobsummerwill** [comment]
OK - I think that https://github.com/ethereum/homebrew-ethereum/pull/56 should address this.

**Comment by bobsummerwill** [comment]
Hey @area!    So 9 hours later, my clean install including that #56 PR is getting all the way to cpp-ethereum make install and failing on the verify_app again.   Ha ha!

**Comment by area** [comment]
Hmmm, that's exactly what https://github.com/ethereum/webthree-helpers/pull/83 was meant to fix. I'd check to see what files it `find`s and see if it's being caught or what the output is from running `install_name_tool`

I'll take a look too, but I don't currently have `qt5 --with-dbus` installed, so I'll be a good few hours at least... ;)

**Comment by bobsummerwill** [comment]
I know.    9 fucking hours for me.

Would be great to strip `--with-d-bus` out if it turns out that we don't actually need it.    Then we can just use the prebuilt bottle!

**Comment by bobsummerwill** [comment]
Thanks for looking.
I should be to run those checks on my machine if you tell me what to do ... ?

**Comment by area** [comment]
I'd start with replacing the relevant lines with...
```
for j in $(find $i/ -name *.app); do
	echo "For app:" $j
	EXEC_NAME=$j/Contents/MacOS/$(basename -s .app $j)
	echo "Exec name:" $EXEC_NAME
	otool -L $EXEC_NAME | grep -o /usr/local.*dylib | while read -a innerlibs ; do
		echo "Trying to change linked path from ${innerlibs[0]} @loader_path/../Frameworks/`basename ${innerlibs[0]}`
		install_name_tool -change ${innerlibs[0]} @loader_path/../Frameworks/`basename ${innerlibs[0]}` $EXEC_NAME
	done
done
exit 1
```

And trying to compile. I've not tested that, so hopefully no syntax errors...

**Comment by michaelmarks** [comment]
I noticed the binary I built has a different dylib path compared to the one that's installed.
Run `otool -L`on the built QtWebEngineProcess.app versus the one in /usr/local/Cellar. I haven't dug thru the makefile to understand everything, but wanted to add this now

The one in /usr/local/Cellar has a relative location for the dylib
`@loader_path/../Frameworks/libdbus-1.3.dylib`
while the one I built has an absolute path
`/usr/local/opt/d-bus/lib/libdbus-1.3.dylib`

**Comment by bobsummerwill** [comment]
Hmm.   See above, @area.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/homebrew-ethereum/commit/5335072159893823594f7a18aa97e219fd123703.   So the Formula is fixed now so that Qt with d-bus dependency is part of the formula.

Now it's just down to whether we have dangling 'verify_app' left.

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/265.
