### ISSUE TITLE
Qt5Core error when installing cpp-ethereum

### ISSUE THREAD

**Issue by HalfbakedFlunky** [ethereum/homebrew-ethereum#55]
On OSX 10.11.2

When performing the install 
"brew install cpp-ethereum --with-gui"

Last 15 lines from /Users/andrew/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)

**Comment by bobsummerwill** [comment]
Looks like you're hitting the same issue as #53, so I'll close this as a dupe.

**Comment by bobsummerwill** [comment]
Oops - can't close this.
@caktux Please could you do the honors?   And/or add grant me rights on this repo so I can do it myself in the future.
