### ISSUE TITLE
Homebrew broken for cpp-ethereum?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/homebrew-ethereum#57]
Look at https://github.com/ethereum/homebrew-ethereum/commits/master.

There hasn't been an update to update cpp-ethereum.rb since Feb 7th, which looks suspicious to me.

What triggers that to be updated?   Changes to webthree-umbrella?

https://github.com/ethereum/webthree-umbrella/commits/develop

Looks like this hasn't updated with the 1.1.2 or 1.1.3 releases.

Is something broken?   @caktux @chriseth @LefterisJP?

**Comment by LefterisJP** [comment]
A succesfull release build of Jenkins has as its last step an upload of a new .rb file.

**Comment by bobsummerwill** [comment]
Like this chain ...

http://52.28.164.97/job/ethbinaries-release/26/
http://52.28.164.97/job/ethbinaries-build/220/
http://52.28.164.97/job/ethbinaries-build/220/label=macosx_slave/

**Comment by bobsummerwill** [comment]
Hmm ... http://52.28.164.97/job/ethbinaries-build/216/label=macosx_slave/console

>>> Starting the script to upload .rb file to homebrew ethereum
fatal: destination path 'homebrew-ethereum' already exists and is not an empty directory.
/var/folders/9n/9b8qccpj7156nx09l9v9jqn00000gp/T/build_step_template691454577147387621.sh: line 9: cd: homebrew-ethereum: Not a directory

Looks like "release" was stagnant for webthree-umbrella since November, then @chriseth did a big flush on February 8th, and that .rb deploy isn't working.

I'll keep going here, then flip to develop.

**Comment by bobsummerwill** [comment]
http://52.28.164.97/job/ethbinaries-build/configure
http://52.28.164.97/configfiles/show?id=org.jenkinsci.plugins.managedscripts.ScriptConfig1442588168169

Hmm.   Maybe this:

    cp webthree-umbrella/build/cpp-ethereum.rb homebrew-ethereum

Should be:

cp webthree-umbrella/build/cpp-ethereum.rb homebrew-ethereum/

**Comment by LefterisJP** [comment]
trailing slash should make no difference

**Comment by bobsummerwill** [comment]
So yeah ... not sure what's broken here, but it's broken :-)    None of the updates of this file into homebrew-ethereum have succeeded since Feb 7th.

**Comment by bobsummerwill** [comment]
OK, so it's http://stackoverflow.com/questions/9864728/how-to-get-git-to-clone-into-current-directory, which is trying to git clone into a non-empty directory.   The two projects cannot be cleaning correctly between each running.

**Comment by bobsummerwill** [comment]
Fixed with a change to the upload script within Jenkins.

The previous code was removing the git clone at the end of the script, not defensively at the start too.   That pattern broke when the release branch was built on Feb 8th.

One has gone through again tonight - https://github.com/ethereum/homebrew-ethereum/commit/5335072159893823594f7a18aa97e219fd123703 - and that has pulled in the Formula updates too.

**Comment by LefterisJP** [comment]
:+1:
