### ISSUE TITLE
Building Homebrew OS X El Capitan with --with-gui

### ISSUE THREAD

**Issue by flaviocordova** [ethereum/homebrew-ethereum#62]
When I build the homebrew version (following the instructions @ http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/osx-homebrew.html) using the --with-gui option I get a compilation error according to the log bellow.

```
#include <QtWebEngineWidgets/QWebEngineCallback>
         ^
1 error generated.
make[2]: *** [alethzero/alethzero/CMakeFiles/AlethZero.dir/plugins/browser/Browser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [alethzero/alethzero/CMakeFiles/AlethZero.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by bobsummerwill** [comment]
Thanks for the note, @flaviocordova!

This happened when Homebrew updated from Qt 5.5 to Qt 5.6.     It is a rolling release manager, which means that our dependencies can change underneath us at any time.

I got this one myself yesterday and committed a fix to webthree-umbrella [here](https://github.com/ethereum/webthree-umbrella/commit/d489843e90b956277082c862bc5072eb47348f66) but it looks like it hasn't gone around the loop yet in Homebrew.    I believe the nightly build will happen in a few hours time.

I would suggest that you try this again TOMORROW and close the issue if it starts working for you at that point.   I think it will.     I might even work right now, actually.    Let me know!   Thanks.

**Comment by bobsummerwill** [comment]
Actually.   I'll close this, because I know exactly what it is.    Please can you re-open it if you still get the issue tomorrow?   Thanks!

**Comment by bobsummerwill** [comment]
Homebrew refreshed an hour ago!  https://github.com/ethereum/homebrew-ethereum/commit/1313319a4214f2fa2caea9155e3a65022e449325

**Comment by The18thWarrior** [comment]
I'm getting cmake error when installing cpp-ethereum with the --with-gui option. The error is below: 

`-- info='external prerequisites found:
f='/tmp/cpp-ethereum20160406-56707-1puevod/alethzero/alethzero/AlethZero.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess'
external_prereqs='/usr/local/Cellar/qt5/5.6.0/lib/QtCore.framework/Versions/5/QtCore;/usr/local/Cellar/qt5/5.6.0/lib/QtGui.framework/Versions/5/QtGui;/usr/local/Cellar/qt5/5.6.0/lib/QtNetwork.framework/Versions/5/QtNetwork;/usr/local/Cellar/qt5/5.6.0/lib/QtPositioning.framework/Versions/5/QtPositioning;/usr/local/Cellar/qt5/5.6.0/lib/QtQml.framework/Versions/5/QtQml;/usr/local/Cellar/qt5/5.6.0/lib/QtQuick.framework/Versions/5/QtQuick;/usr/local/Cellar/qt5/5.6.0/lib/QtWebChannel.framework/Versions/5/QtWebChannel;/usr/local/Cellar/qt5/5.6.0/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore;/usr/local/opt/d-bus/lib/libdbus-1.3.dylib'
'
-- 
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/BundleUtilities.cmake:975 (message):
  error: verify_app failed
Call Stack (most recent call first):
  alethzero/alethzero/cmake_install.cmake:34 (verify_app)
  alethzero/cmake_install.cmake:33 (include)
  cmake_install.cmake:37 (include)
  
`
