### ISSUE TITLE
Running GPU on MacBookPro Intel 

### ISSUE THREAD

**Issue by flaviocordova** [ethereum/homebrew-ethereum#63]
I built cpp-ethereum using homebrew but when I try to use GPU processing it shows an error (I guess).. I think it's related to my GPU card (Intel HD Graphics 4000 1536 MB) because it works fine when using CPU.

Is it supported now ? If no, will it be or is there any reason why it won't?

using iStats to monitor it looks like GPU memory is even allocated but it stops running right after. 

```
$eth -M -G
cpp-ethereum, a C++ Ethereal client
[OPENCL]:Found suitable OpenCL device [HD Graphics 4000] with 1610612736 bytes of GPU memory
Benchmarking on platform: { "platform": "Apple", "device": "HD Graphics 4000", "version": "OpenCL 1.2 " }
Preparing DAG...
Warming up...
  ℹ  22:46:42.455|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  22:46:42.457|gpuminer0  Initialising miner...
[OPENCL]:Using platform: Apple
[OPENCL]:Using device: HD Graphics 4000(OpenCL 1.2 )
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
Abort trap: 6

```

**Comment by bobsummerwill** [comment]
I'm afraid you are out of luck.   Your GPU doesn't have enough memory for mining.   2Gb appears to be the minimum requirement.

High-end GPUs haven't been a priority for Apple, which is also why Oculus isn't coming to Macs in any hurry.    Most miners are using Linux, with some using Windows.

Sorry!
