### ISSUE TITLE
Revision 412 no longer exists

### ISSUE THREAD

**Issue by Arachnid** [ethereum/homebrew-ethereum#69]
The current brewfile points to revision 412, which no longer exists in the Ethereum build repository, so building fails.

**Comment by bobsummerwill** [comment]
Hey @Arachnid,

Just to verify, you're seeing this on El Capitan for `cpp-ethereum`, right?

If so, yes, you are the victim of WIP on adding support for El Capitan AT ALL :-)

Being tracked as https://github.com/ethereum/webthree-umbrella/issues/454.   I'll add you on that and close this one.

**Comment by Arachnid** [comment]
No, I'm on Yosemite - there's no build 412 for Yosemite in the repo, either.

**Comment by bobsummerwill** [comment]
There isn't?   Yuck.   Reopening.

**Comment by bobsummerwill** [comment]
Actually - I'll close this again.   Have added as a bullet point TODO in the other issue.
