### ISSUE TITLE
brew upgrade hangs on boost

### ISSUE THREAD

**Issue by sclopit** [ethereum/homebrew-ethereum#70]
attempts to invoke

brew upgrade

are unsuccessful due to brew freezing/hanging when attempting to upgrade package 'boost'.

a Google search reveals that the problem appears to be widespread.

Stefanos-MBP:~ stefano$ brew upgrade
==> Upgrading 28 outdated packages, with result:
boost 1.60.0_2, boost-python 1.60.0, ethereum/ethereum/cpp-ethereum 1.2.4, cryptopp 5.6.3_1, curl 7.49.0, ffmpeg 3.0.2, git 2.8.3, gmp 6.1.0, go 1.6.2, jsoncpp 1.6.5, libjson-rpc-cpp 0.6.0_1, libmicrohttpd 0.9.47_1, mercurial 3.8.2, miniupnpc 2.0, multirust 0.8.0, openssl 1.0.2h_1, ethcore/ethcore/parity 1.1.0, pkg-config 0.29.1, pyqt 4.11.4, python 2.7.11, qt 4.8.7_2, rocksdb 4.5.1, ruby 2.3.1, sip 4.18, sqlite 3.13.0, texi2html 5.0, x264 r2668, xz 5.2.2
==> Upgrading boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boo
Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/9e56b45/boost/boost1_60_0_python_class_metadata.diff
Already downloaded: /Library/Caches/Homebrew/boost--patch-1a470c3a2738af409f68e3301eaecd8d07f27a8965824baf8aee0adef463b844.diff
==> Patching
patching file boost/graph/adjacency_matrix.hpp
==> Applying boost1_60_0_python_class_metadata.diff
patching file boost/python/object/class_metadata.hpp
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_2 --libdir=/usr/local/Cellar/boost/1.60.0_2/lib --without-icu --
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_2 --libdir=/usr/local/Cellar/boost/1.60.0_2/lib -d2 -j4 --layout=tagged --

[at this point brew gets stuck]

**Comment by bobsummerwill** [comment]
Hey Stefano!

Well that sucks.   I assume that your `brew upgrade` was immediately after a `brew update`?   Are you using Yosemite or El Capitan?

Have you tried a `brew doctor`?   Please do.    Might also be worth checking if your xcode needs updating.

If none of that moves you forward we should log an issue with Homebrew (or see if there is an open ticket already - https://github.com/Homebrew/legacy-homebrew/issues

Best wishes!

**Comment by sclopit** [comment]
Hi Bob,

thanks for checking on this.

1) yes, I did a 'brew update' immediately before the 'brew upgrade'
2) I am using El Capitan 10.11.4
3) my Xcode is up to date
4) eventually (after 24 minutes) boost did upgrade (it may be a good idea
to warn Ethereum users that 'brew upgrade' may take a loooong time with no
sign of progress)
5) I eventually run into a different problem (concerning llvm37) see below.
note that brew tells you that there was an Error but not what to do about
it. Also, installing ethereum *after* the brew error was flagged seemed to
work (see below). This is extremely confusing as one is simultaneously told
that something is wrong and that everything is OK with one's brew/ehereum
setup

so my more general point is that while

https://www.ethereum.org/cli

makes it look as if installing ethereum with brew is stroll on the beach,
my experience is more of walking barefoot on a beach full of broken glass
shards...

anything you could do to anticipate/mitigate this will greatly enhance the
experience of Ethereum newcomers.

thanks in advance

stefano

*Stefanos-MBP:~ stefano$ brew upgrade*

*==>** Upgrading 28 outdated packages, with result:*

*boost 1.60.0_2, boost-python 1.60.0, ethereum/ethereum/cpp-ethereum 1.2.4,
cryptopp 5.6.3_1, curl 7.49.0, ffmpeg 3.0.2, git 2.8.3, gmp 6.1.0, go
1.6.2, jsoncpp 1.6.5, libjson-rpc-cpp 0.6.0_1, libmicrohttpd 0.9.47_1,
mercurial 3.8.2, miniupnpc 2.0, multirust 0.8.0, openssl 1.0.2h_1,
ethcore/ethcore/parity 1.1.0, pkg-config 0.29.1, pyqt 4.11.4, python
2.7.11, qt 4.8.7_2, rocksdb 4.5.1, ruby 2.3.1, sip 4.18, sqlite 3.13.0,
texi2html 5.0, x264 r2668, xz 5.2.2*

*==>** Upgrading boost*

*==>** Downloading
https://downloads.sourceforge.net/project/boost/boost/1.60.0/boo
<https://downloads.sourceforge.net/project/boost/boost/1.60.0/boo>*

*Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2*

*==>** Downloading
https://raw.githubusercontent.com/Homebrew/patches/9e56b45/boost/boost1_60_0_python_class_metadata.diff
<https://raw.githubusercontent.com/Homebrew/patches/9e56b45/boost/boost1_60_0_python_class_metadata.diff>*

*Already downloaded:
/Library/Caches/Homebrew/boost--patch-1a470c3a2738af409f68e3301eaecd8d07f27a8965824baf8aee0adef463b844.diff*

*==>** Patching*

*patching file boost/graph/adjacency_matrix.hpp*

*==>** Applying boost1_60_0_python_class_metadata.diff*

*patching file boost/python/object/class_metadata.hpp*

*==>** ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_2
--libdir=/usr/local/Cellar/boost/1.60.0_2/lib --without-icu --*

*==>** ./b2 headers*

*==>** ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_2
--libdir=/usr/local/Cellar/boost/1.60.0_2/lib -d2 -j4 --layout=tagged --*

*🍺  /usr/local/Cellar/boost/1.60.0_2: 11,139 files, 437.7M, built in 24
minutes 13 seconds*

*==>** Upgrading boost-python*

*==>** Downloading
https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
<https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2>*

*==>** Downloading from
http://netix.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
<http://netix.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2>*

*########################################################################
100.0%*

*==>** ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.60.0
--libdir=/usr/local/Cellar/boost-python/1.60.0/lib --with*

*==>** ./b2 --build-dir=build-python --stagedir=stage-python python=2.7
--prefix=/usr/local/Cellar/boost-python/1.60.0 --libdi*

*🍺  /usr/local/Cellar/boost-python/1.60.0: 274 files, 15M, built in 4
minutes 3 seconds*

*Error**: No available formula with the name "llvm37" (dependency of
ethereum/ethereum/cpp-ethereum)*


*Stefanos-MBP:~ stefano$ brew upgrade*

*==>** Upgrading 26 outdated packages, with result:*

*ethereum/ethereum/cpp-ethereum 1.2.4, cryptopp 5.6.3_1, curl 7.49.0,
ffmpeg 3.0.2, git 2.8.3, gmp 6.1.0, go 1.6.2, jsoncpp 1.6.5,
libjson-rpc-cpp 0.6.0_1, libmicrohttpd 0.9.47_1, mercurial 3.8.2, miniupnpc
2.0, multirust 0.8.0, openssl 1.0.2h_1, ethcore/ethcore/parity 1.1.0,
pkg-config 0.29.1, pyqt 4.11.4, python 2.7.11, qt 4.8.7_2, rocksdb 4.5.1,
ruby 2.3.1, sip 4.18, sqlite 3.13.0, texi2html 5.0, x264 r2668, xz 5.2.2*

*Error**: No available formula with the name "llvm37" (dependency of
ethereum/ethereum/cpp-ethereum)*

*Stefanos-MBP:~ stefano$ brew tap ethereum/ethereum*

*Stefanos-MBP:~ stefano$ brew install ethereum*

*Warning**: ethereum/ethereum/ethereum-1.4.4 already installed*

*Stefanos-MBP:~ stefano$ *

On Sun, May 22, 2016 at 8:00 AM, Bob Summerwill <notifications@github.com>
wrote:

> Hey Stefano!
>
> Well that sucks. I assume that your brew upgrade was immediately after a brew
> update? Are you using Yosemite or El Capitan?
>
> Have you tried a brew doctor? Please do. Might also be worth checking if
> your xcode needs updating.
>
> If none of that moves you forward we should log an issue with Homebrew (or
> see if there is an open ticket already -
> https://github.com/Homebrew/legacy-homebrew/issues
>
> Best wishes!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/homebrew-ethereum/issues/70#issuecomment-220816032>
>



-- 
Stefano Bertolo 408A rue de Neudorf Luxembourg L2222 Luxembourg
00352 621 901062 (cell)                              Skype: stefano.bertolo
00352 26521670 (home)                              Twitter: sclopit
http://www.linkedin.com/in/stefanobertolo
http://www.okkam.org/entity/ed5bdc09-ca66-4435-b48e-6df558315fa1

**Comment by bobsummerwill** [comment]
Yes, OS X is not a bed of roses, I am afraid.   It is a fundamental issue with Homebrew.   See https://github.com/ethereum/webthree-umbrella/issues/118.

You'll see a "Here be dragons" if you follow the link from that page to http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html, but we should probably extend that caution backto http://ethereum.org, eh, @alexvandesande?

For the llvm37 issue, I thought that we recently fixed that one, but it appears that the fix was caught up within a pending update to llvm38 (https://github.com/ethereum/homebrew-ethereum/pull/67/files), so I've just redone that fix manually.     The issue only shows on a completely vanilla machine (like yours!) so we didn't notice it.

Please can you do another `brew update`, `brew upgrade`, `brew install cpp-ethereum` and report back?   Thanks!

**Comment by bobsummerwill** [comment]
BTW - RE: "eventually (after 24 minutes) boost did upgrade".

When I first started looking at this in November or so of last year we were building LLVM, Qt and Chromium from source, and it could take 16 hours or more.   Just terrible.    It is an ongoing battle to get OS X into a non-appalling state.

`brew install cpp-ethereum --with-gui` still has to built Qt5 from source, and is unacceptably awful.

Hopefully your quest is close to done now.

**Comment by bobsummerwill** [comment]
YEP ... "anything you could do to anticipate/mitigate this will greatly enhance the
experience of Ethereum newcomers." ... very much so.   It's what I'm working on most of the time.

This ongoing and long-fought issue will help a lot:   https://github.com/ethereum/webthree-umbrella/issues/454

But we should make the http://ethereum.org/cli docs reflect the pain more too, for sure.

**Comment by sclopit** [comment]
Thanks Bob,

the sequence you requested me to test worked without problem

*Stefanos-MBP:~ stefano$ brew update*

*Already up-to-date.*

*Stefanos-MBP:~ stefano$ brew upgrade*

*Stefanos-MBP:~ stefano$ brew install cpp-ethereum*

*Warning**: ethereum/ethereum/cpp-ethereum-1.2.4 already installed*


[although I am now puzzled why you asked me to test the C++ version
cpp-ethereum, when the discussion was about the Go version, which I have
*also* 'brew install ethereum/ethereum' without problems after first
tapping it]


that said, the picture below is what happens when I invoke


geth --verbosity=6 console


the CPU is pinned so hard (notice the spinning beach ball) that
nothing else works (I cannot even cut and paste the output of the terminal,
that's why I had to take the picture with my phone).


the CPU pinning is behavior that I can consistently reproduce, also when I
start the Ethereum Wallet.


the message on which everything blocks talks about a 'Genesis block
mismatch'.


Could it be that I have some Etherem block(s) stuck somewhere on my
computer that I should just flush/delete in order for the geth client to
start fresh (and not die)?


thanks again in advance


stefano




On Sun, May 22, 2016 at 9:15 AM, Bob Summerwill <notifications@github.com>
wrote:

> Yes, OS X is not a bed of roses, I am afraid. It is a fundamental issue
> with Homebrew. See ethereum/webthree-umbrella#118
> <https://github.com/ethereum/webthree-umbrella/issues/118>.
>
> You'll see a "Here be dragons" if you follow the link from that page to
> http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html,
> but we should probably extend that caution backto http://ethereum.org,
> eh, @alexvandesande <https://github.com/alexvandesande>?
>
> For the llvm37 issue, I thought that we recently fixed that one, but it
> appears that the fix was caught up within a pending update to llvm38 (
> https://github.com/ethereum/homebrew-ethereum/pull/67/files), so I've
> just redone that fix manually. The issue only shows on a completely vanilla
> machine (like yours!) so we didn't notice it.
>
> Please can you do another brew update, brew upgrade, brew install
> cpp-ethereum and report back? Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/homebrew-ethereum/issues/70#issuecomment-220818155>
>



-- 
Stefano Bertolo 408A rue de Neudorf Luxembourg L2222 Luxembourg
00352 621 901062 (cell)                              Skype: stefano.bertolo
00352 26521670 (home)                              Twitter: sclopit
http://www.linkedin.com/in/stefanobertolo
http://www.okkam.org/entity/ed5bdc09-ca66-4435-b48e-6df558315fa1

**Comment by sclopit** [comment]
On Sun, May 22, 2016 at 9:23 AM, Bob Summerwill <notifications@github.com>
wrote:

> YEP ... "anything you could do to anticipate/mitigate this will greatly
> enhance the
> experience of Ethereum newcomers." ... very much so. It's what I'm working
> on most of the time.
>
> This ongoing and long-fought issue will help a lot:
> ethereum/webthree-umbrella#454
> <https://github.com/ethereum/webthree-umbrella/issues/454>
>

good lord!

I don't envy you...

many thanks for your work on this front

stefano




-- 
Stefano Bertolo 408A rue de Neudorf Luxembourg L2222 Luxembourg
00352 621 901062 (cell)                              Skype: stefano.bertolo
00352 26521670 (home)                              Twitter: sclopit
http://www.linkedin.com/in/stefanobertolo
http://www.okkam.org/entity/ed5bdc09-ca66-4435-b48e-6df558315fa1

**Comment by bobsummerwill** [comment]
The issues you hit were all problems with `cpp-ethereum` dependencies.    If you were only using `ethereum` then you wouldn't have hit any of them.   Well, unless you had other packages installed which used `boost`.    The `llvm37` one was happening when your previously installed `cpp-ethereum` was being updated.

I guess you installed both `ethereum` and `cpp-ethereum` at some point in the past?

For your geth pinning issues, I would suggest that you talk to the geth team on https://gitter.im/ethereum/go-ethereum or log an issue on https://github.com/ethereum/go-ethereum.   I'm afraid I can't help you there.   I work on the C++ client, not the Go client.   Best wishes!

We'll leave this issue open until I address the documentation.   Thanks.

**Comment by bobsummerwill** [comment]
All reworked since.
