### ISSUE TITLE
Failed to download "cpp-ethereum" on Mac OS X El-Capitan

### ISSUE THREAD

**Issue by zenoid2** [ethereum/homebrew-ethereum#78]
brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Downloading https://build.ethereum.org/cpp-binaries-data/brew_receipts/cpp-ethereum-1.2.9.el_capitan.bottle.491.tar.gz
==> Downloading from https://builds.ethereum.org/cpp-binaries-data/brew_receipts/cpp-ethereum-1.2.9.el_capitan.bottle.491.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "cpp-ethereum"

---
Im not able to install solc ... is there anywhere an known solution for installing solidity on a mac?
Thank you

**Comment by bobsummerwill** [comment]
Hey @zenoid2,   Sorry about that.

We are rebuilding our automation right now, and that bottle is broken.

You should be able to workaround that with `brew install cpp-ethereum --build-from-source", or you can use the node version of solidity (http://solidity.readthedocs.io/en/latest/installing-solidity.html#npm-node-js).

Ongoing work being tracked as https://github.com/ethereum/webthree-umbrella/issues/599.   Best wishes!
