### ISSUE TITLE
Make fails: *** [all] Error 2

### ISSUE THREAD

**Issue by miohtama** [ethereum/homebrew-ethereum#81]
I am not sure what's going on as I cannot spot clear error output from `brew upgrade cpp-ethereum`:

    ==> Cloning https://github.com/ethereum/webthree-umbrella.git
    Updating /Users/mikko/Library/Caches/Homebrew/cpp-ethereum--git
    ==> Checking out branch develop
    warning: unable to rmdir alethzero: Directory not empty
    warning: unable to rmdir mix: Directory not empty
    warning: unable to rmdir web3.js: Directory not empty
    Synchronizing submodule url for 'evmjit'
    ==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.2.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DC
    ==> make
    Last 15 lines from /Users/mikko/Library/Logs/Homebrew/cpp-ethereum/02.make:
    [ 95%] Building CXX object libethereum/test/CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o
    cd /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test && /usr/local/Library/Homebrew/shims/super/clang++   -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libweb3core -isystem /tmp/cpp-ethereum-20160729-76315-1xrxop/webthree-helpers/utils -isystem /usr/local/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop -I/tmp/cpp-ethereum-20160729-76315-1xrxop/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/evmjit/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/libethash-cl  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o -c /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test/libethereum/TransactionTests.cpp
    make[1]: *** [webthree/libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 95%] Building CXX object libethereum/test/CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o
    cd /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test && /usr/local/Library/Homebrew/shims/super/clang++   -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libweb3core -isystem /tmp/cpp-ethereum-20160729-76315-1xrxop/webthree-helpers/utils -isystem /usr/local/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop -I/tmp/cpp-ethereum-20160729-76315-1xrxop/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/evmjit/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/libethash-cl  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o -c /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test/libweb3core/crypto.cpp
    [ 96%] Building CXX object libethereum/test/CMakeFiles/testeth.dir/libevm/vm.cpp.o
    cd /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test && /usr/local/Library/Homebrew/shims/super/clang++   -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libweb3core -isystem /tmp/cpp-ethereum-20160729-76315-1xrxop/webthree-helpers/utils -isystem /usr/local/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop -I/tmp/cpp-ethereum-20160729-76315-1xrxop/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/evmjit/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/libethash-cl  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libevm/vm.cpp.o -c /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test/libevm/vm.cpp
    [ 96%] Building CXX object libethereum/test/CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o
    cd /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test && /usr/local/Library/Homebrew/shims/super/clang++   -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libweb3core -isystem /tmp/cpp-ethereum-20160729-76315-1xrxop/webthree-helpers/utils -isystem /usr/local/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop -I/tmp/cpp-ethereum-20160729-76315-1xrxop/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/evmjit/include -I/tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/libethash-cl  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o -c /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test/external-dependencies/boost.cpp
    [ 96%] Linking CXX executable testeth
    cd /tmp/cpp-ethereum-20160729-76315-1xrxop/libethereum/test && /usr/local/Cellar/cmake/3.6.0_1/bin/cmake -E cmake_link_script CMakeFiles/testeth.dir/link.txt --verbose=1
    /usr/local/Library/Homebrew/shims/super/clang++   -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testeth.dir/BlockChainHelper.cpp.o CMakeFiles/testeth.dir/boostTest.cpp.o CMakeFiles/testeth.dir/Stats.cpp.o CMakeFiles/testeth.dir/TestHelper.cpp.o CMakeFiles/testeth.dir/TestUtils.cpp.o CMakeFiles/testeth.dir/fuzzTesting/createRandomTest.cpp.o CMakeFiles/testeth.dir/fuzzTesting/fuzzHelper.cpp.o CMakeFiles/testeth.dir/libethcore/commonjs.cpp.o CMakeFiles/testeth.dir/libethcore/dagger.cpp.o CMakeFiles/testeth.dir/libethcore/difficulty.cpp.o CMakeFiles/testeth.dir/libethcore/icap.cpp.o CMakeFiles/testeth.dir/libethcore/keymanager.cpp.o CMakeFiles/testeth.dir/libethereum/AccountDiff.cpp.o CMakeFiles/testeth.dir/libethereum/Block.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChain.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChainInsert.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChainTests.cpp.o CMakeFiles/testeth.dir/libethereum/BlockQueue.cpp.o CMakeFiles/testeth.dir/libethereum/ClientBase.cpp.o CMakeFiles/testeth.dir/libethereum/GasPricer.cpp.o CMakeFiles/testeth.dir/libethereum/Genesis.cpp.o CMakeFiles/testeth.dir/libethereum/State.cpp.o CMakeFiles/testeth.dir/libethereum/StateOriginal.cpp.o CMakeFiles/testeth.dir/libethereum/Transaction.cpp.o CMakeFiles/testeth.dir/libethereum/TransactionQueue.cpp.o CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o CMakeFiles/testeth.dir/libevm/vm.cpp.o CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o  -o testeth  /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libcryptopp.dylib ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libminiupnpc.dylib /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libcryptopp.dylib -framework OpenCL libtestutils/libtestutils.dylib /usr/local/lib/libboost_unit_test_framework-mt.a ../libethashseal/libethashseal.dylib ../libethereum/libethereum.dylib ../libevm/libevm.dylib ../libethcore/libethcore.dylib ../libevmcore/libevmcore.dylib ../evmjit/libevmjit/libevmjit.0.9.0.2.dylib ../../libweb3core/libp2p/libp2p.dylib ../../libweb3core/libdevcrypto/libdevcrypto.dylib ../../libweb3core/libdevcore/libdevcore.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a ../../webthree-helpers/utils/libscrypt/libscrypt.dylib ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libgmp.dylib /usr/local/lib/libminiupnpc.dylib /usr/local/lib/libboost_regex-mt.a ../libethash-cl/libethash-cl.dylib ../libethash/libethash.dylib /usr/local/lib/libcryptopp.dylib -framework OpenCL
    [ 96%] Built target testeth
    make: *** [all] Error 2

    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/brew):
      https://github.com/ethereum/homebrew-ethereum/issues

**Comment by miohtama** [comment]
Looks like a duplicate of closed issue https://github.com/ethereum/homebrew-ethereum/issues/29

**Comment by bobsummerwill** [comment]
Hey @miohtama,
This is known broken.   I am working on it.

Please build from source for now.   Thanks!

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/macos.html

The pending v1.3.1 release will clean up all this messy work in progress.    Our Jenkins instance died on us, and I've been rebuilding our pipelines.   Not quite there!
