### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by GYESS1** [ethereum/homebrew-ethereum#87]
can anyone help me  the cpu mining works but not the GPU ? 

Mac-Pro:share HD2$ eth --frontier -b --genesis /tmp/genesis_block.json -m on -G --opencl-device 0 -F     MY POOL INFO    --disable-submit-hashrate
cpp-ethereum, a C++ Ethereum client
[OPENCL]:Found suitable OpenCL device [GeForce GTX 570] with 2684354560 bytes of GPU memory
  ℹ  20:55:07.567|  Loading full DAG of seedhash: #0f4bcc94…
  ℹ  20:55:07.568|gpuminer0  workLoop 0 #00000000… #98c461e5…
  ℹ  20:55:07.569|gpuminer0  Initialising miner...
[OPENCL]:Using platform: Apple
[OPENCL]:Using device: GeForce GTX 570(OpenCL 1.1 )
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
Trace/BPT trap: 5

Mac-Pro:share HD2$ ethminer --list-devices
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 570
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2684354560
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 671088640
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

**Comment by GYESS1** [comment]
Mac-Pro:share HD2$ ethminer --list-devices
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 570
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2684354560
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 671088640
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

**Comment by bobsummerwill** [comment]
Hey @GYESS1!
Please ask for help on https://gitter.im/ethereum/minercommunitysupport.   Best wishes!
