### ISSUE TITLE
Unable to install go-ethereum 

### ISSUE THREAD

**Issue by ghost** [ethereum/homebrew-ethereum#89]
The following message has displayed to me each time I try to install Geth for ethereum. What is the issue? 

_Last 15 lines from /Users/iivri.andre/Library/Logs/Homebrew/ethereum/02.make:
2016-10-17 13:25:48 -0500

make
all

build/env.sh go run build/ci.go install
make: build/env.sh: No such file or directory
make: **\* [all] Error 1_

**Comment by FUSED-ID** [comment]
Any resolution here ? stranded on my GETH Build

**Comment by kramer65** [comment]
I've also go the same problem. Any ideas?

**Comment by trumhemcut** [comment]
I faced the same issue, please help

**Comment by kramer65** [comment]
Ok, I found the issue. The problem was that line endings where in dos style.

So to recursively convert line endings to unix I ran:

    find . -type f -print0 | xargs -0 -n 1 -P 4 dos2unix

and then tried building again. That fixed it. 

I hope this helps someone else here.

**Comment by jackcasey** [comment]
I can't install go-ethereum 1.5.9 on macosx using homebrew. I get the following error:

```
~ $ brew install ethereum
Updating Homebrew...
==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/jack/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.5.9
==> go env
==> make all
Last 15 lines from /Users/jack/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/whisper/whisperv5
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/whisper/shhapi
github.com/ethereum/go-ethereum/eth/filters
github.com/ethereum/go-ethereum/eth/fetcher
github.com/ethereum/go-ethereum/miner
github.com/ethereum/go-ethereum/light
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/core/vm/runtime
github.com/ethereum/go-ethereum/cmd/ethtest
util.go:43: exit status 2
exit status 1
make: *** [all] Error 1
```

This is with Xcode 7.2.1 and `brew doctor` looking pretty fine

**Comment by jackcasey** [comment]
Looks like my issue is back at the go-ethereum source: https://github.com/ethereum/go-ethereum/issues/3713

**Comment by hynese** [comment]
I'm also getting this error

```
make
all

build/env.sh go run build/ci.go install
make: build/env.sh: No such file or directory
make: *** [all] Error 1
```

OSX, 10.12.3

**Comment by piotrgrudzien** [comment]
Getting the following error when installing ethereum either using homebrew or building from source (following instructions from [here](https://ethereum.gitbooks.io/frontier-guide/content/installing_mac.html))

`==> Checking out tag v1.6.5
==> go env
==> make all
Last 15 lines from /Users/piotrgrudzien/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/vendor/bazil.org/fuse/fs
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/cast5
github.com/ethereum/go-ethereum/vendor/github.com/Azure/go-autorest/autorest/azure
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/elgamal
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/s2k
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/packet
github.com/ethereum/go-ethereum/internal/guide
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-storage-go
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp
github.com/ethereum/go-ethereum/internal/build
util.go:44: exit status 2
exit status 1
make: *** [all] Error`

**Comment by fjl** [comment]
Please provide more info about macOS version, go version and the full log if possible.

**Comment by piotrgrudzien** [comment]
`go version go1.8.3 darwin/amd64`

`ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2009`

brew update && brew reinstall ethereum
Already up-to-date.
Warning: Calling build.build_bottle? is deprecated!
Use build.bottle? instead.
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:37:in reinstall_formula

==> Reinstalling ethereum/ethereum/ethereum 
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/piotrgrudzien/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.6.5
==> go env
==> make all
Last 15 lines from /Users/piotrgrudzien/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/vendor/bazil.org/fuse/fs
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/cast5
github.com/ethereum/go-ethereum/vendor/github.com/Azure/go-autorest/autorest/azure
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/elgamal
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/s2k
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/packet
github.com/ethereum/go-ethereum/internal/guide
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-storage-go
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp
github.com/ethereum/go-ethereum/internal/build
util.go:44: exit status 2
exit status 1
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Unable to install go-ethereum  https://github.com/ethereum/homebrew-ethereum/issues/89`

**Comment by vishaldeepak** [comment]
Unable to install from home-brew but due to different issue.

Mac OSX - 10.12.5 (16F73)
Go version - go1.8.3 darwin/amd64

```
➜  ~ brew install ethereum
==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/vishaldeepak/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.6.7
```

It won't continue after that. Just hangs there.

**Comment by fjl** [comment]
We are unable to reproduce this failure, sorry. Please note that you can also use the "geth" formula from homebrew-core. It provides pre-built versions of geth.

**Comment by xwa130** [comment]
I solve the problem using by following instructions below. I don't know the reason, but I completely get rid of `brew` to make it run. (mac)
```
1 install go(I used package)
2 git clone https://github.com/ethereum/go-ethereum
3 cd go-ethereum && git checkout tags/v1.8.2
4 run `find . -type f -print0 | xargs -0 -n 1 -P 4 dos2unix`(if you don't have dos2unix, you could brew one, it does not break anything.)
5 make geth
6 ln -s /path/to/origin/geth /path/to/target/geth
```

**Comment by xwa130** [comment]
I highly suggest community target this problem, cause this really confused me a long time. @fjl

**Comment by hackrose** [comment]
```
make geth 
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=1acefafe2201ba061a58b51afd7a7edf4aa0f120 -s -v ./cmd/geth
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
# github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use refZero (type *_Ctype_struct___CFAllocator) as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:169: cannot use refZero (type *_Ctype_struct___CFAllocator) as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:170: cannot use refZero (type *_Ctype_struct___CFAllocator) as type _Ctype_CFAllocatorRef in argument to func literal
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1

```

Resoled:
```
govendor fetch github.com/rjeczalik/notify
make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=1acefafe2201ba061a58b51afd7a7edf4aa0f120 -s -v ./cmd/geth
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
github.com/ethereum/go-ethereum/accounts/keystore
github.com/ethereum/go-ethereum/dashboard
github.com/ethereum/go-ethereum/internal/ethapi
github.com/ethereum/go-ethereum/node
github.com/ethereum/go-ethereum/eth/gasprice
github.com/ethereum/go-ethereum/eth
github.com/ethereum/go-ethereum/les
github.com/ethereum/go-ethereum/ethstats
github.com/ethereum/go-ethereum/cmd/utils
github.com/ethereum/go-ethereum/cmd/geth
Done building.
Run "/Users/hello/golang/src/github.com/ethereum/go-ethereum/build/bin/geth" to launch geth.


```
