### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ppervoy** [ethereum/homebrew-ethereum#9]
brew install ethereum
==> Installing ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/ethereum--git
==> Checking out branch master
==> Patching
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ethereum/0.7.14-49-5 -DCMAKE_
==> make
Generating moc_KeyEventManager.cpp
Generating moc_MixApplication.cpp
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/ethereum-UUFAZb/CMakeFiles  52
[  5%] Built target mix_automoc
make: *** [all] Error 2

https://gist.github.com/6b63d5c9ae29904ce920

**Comment by caktux** [comment]
looks like an issue with boost, what's the output of `brew info boost` ?

**Comment by ppervoy** [comment]
Please find it below:

boost: stable 1.57.0 (bottled), HEAD
http://www.boost.org
/usr/local/Cellar/boost/1.57.0 (10572 files, 430M) *
  Built from source with: --c++11
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
==> Dependencies
Optional: icu4c ✘
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version

**Comment by ppervoy** [comment]
Any thoughts?

**Comment by caktux** [comment]
Still getting the same errors? master branch was broken so it might have been just that, otherwise maybe try `brew unlink boost && brew link boost`

**Comment by maran** [comment]
Sorry to revive this one but I think I'm encountering the same or a similar problem.


```
brew reinstall cpp-ethereum --stable --with-gui
==> Reinstalling cpp-ethereum with --with-gui
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch master
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/0.8.2-54- -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=R
==> make
Generating moc_StatusPane.cpp
Generating moc_Web3Server.cpp
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/cpp-ethereum20150520-7957-1sdd1dh/CMakeFiles
[ 14%] Built target mix_automoc
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues
```

This is my boost info
```
boost: stable 1.58.0 (bottled), HEAD
http://www.boost.org
/usr/local/Cellar/boost/1.51.0 (9038 files, 238M)
/usr/local/Cellar/boost/1.57.0 (10572 files, 464M)
  Built from source with: --c++11
/usr/local/Cellar/boost/1.58.0 (10718 files, 485M) *
  Built from source with: --c++11
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version
```

Any pointers you could give me @caktux ?
