### ISSUE TITLE
--with-gui option not available for cpp-ethereum

### ISSUE THREAD

**Issue by thatdoorsajar** [ethereum/homebrew-ethereum#93]
I tried to install cpp-ethereum with the `--with-gui` flag but there was a none-blocking error from brew saying the flag was not recognised and so was ignored. cpp-ethereum installed successfully but now when I run `brew info cpp-ethereum` I can see that `--with-gui` is actually not available in the list.

Has this option been deprecated and not referenced in the documentation? If it has been removed what are the steps to install and link AlethZero and Mix IDE to this cpp-ethereum install?

Many thanks

**Comment by dbblackdiamond** [comment]
Hi, I am having the exact same issue. I am trying to troubleshoot an issue with a smart contract and having Mix or AlethZero would be really useful, but I don't seem to be able to compile either of them.

**Comment by chrc** [comment]
Hi,

I am having the exact same issue with the command:
brew reinstall cpp-ethereum --devel --with-gui --successful

brew -v
Homebrew 1.1.6
Homebrew/homebrew-core (git revision 1a517; last commit 2017-01-04)

Thanks by advance.

**Comment by axic** [comment]
Mix/AlethZero was removed from `cpp-ethereum` and they will not come back.
